fix: offset after slider
torin-asakura/drum-in pull request #112
Opened 2023-08-08 20:23 UTC by kalininatonya

2023-08-09 10:20 UTC, Nelfimov requested changes
Фикс для правого края слайдера - ✅
А вот левый край не пофикшен - слайды пропадают раньше конца вьюпорта:

<details>

<img width="1374" alt="Screenshot 2023-08-09 at 13 17 15" src="https://github.com/torin-asakura/drum-in/assets/44067768/d89392b2-6ec1-4bde-b001-d90e6f7bf163">

</details>

2023-08-09 17:15 UTC, kalininatonya commented
> Фикс для правого края слайдера - ✅ А вот левый край не пофикшен - слайды пропадают раньше конца вьюпорта:

Исправила.

2023-08-09 18:42 UTC, Nelfimov requested changes
1. Баг со слайдером выбора курсов пофикшен, молоток!
2. Нужно разобраться с конфликтами проверки пр
3. Пока ты на такой хорошей волне, можно пофиксить все слайдеры

На индексе:

<details>

## Слайдер с фото

Как есть:

![image](https://github.com/torin-asakura/drum-in/assets/44067768/01d826b6-d03b-46d9-963b-4f6910150466)

Как должно быть - видны части предыдущего и следующего фото:

<img width="666" alt="Screenshot 2023-08-09 at 21 32 16" src="https://github.com/torin-asakura/drum-in/assets/44067768/0e81c9d8-44b0-451d-9ecf-4f2171a8461f">

## Слайдер с учениками

Как есть:

![image](https://github.com/torin-asakura/drum-in/assets/44067768/8945b752-9006-418b-80ec-a73540da17c9)

Так же как то что ты пофиксила - оффсет с правой стороны добавить.

Так же для всех слайдеров добавить возможность горизонтального скролла с помощью трекпада.

</details>

2023-08-09 18:56 UTC, Nelfimov requested changes
См. выше

2023-08-10 19:42 UTC, kalininatonya commented
> 1. Баг со слайдером выбора курсов пофикшен, молоток!
> 2. Нужно разобраться с конфликтами проверки пр
> 3. Пока ты на такой хорошей волне, можно пофиксить все слайдеры
> 
> На индексе:

Пофиксила все слайдеры. С конфликтами пока копаю.

2023-08-11 06:39 UTC, Nelfimov requested changes
1. Слайдеры на индексе - ✅
2. Конфликты пр - у тебя такая ошибка:
```shell
TypeCheck run failed

ENOENT: no such file or directory, open '/home/runner/work/drum-in/drum-in/.yarn/virtual/@landing-choose-course-fragment-virtual-761353a221/1/landing/fragments/landing-choose-course/src/slider/desktop-slider/desktop-slider.component.tsx'
```
3. Поправь размер картинок на этом слайдере, отличаются от дизайна:

<details>

![image](https://github.com/torin-asakura/drum-in/assets/44067768/4fc9cc3e-69ce-4df1-8d41-c898f0fff383)

</details>

4. Нашел еще один слайдер для твоих ловких рук - "Как проходит обучение". Те же ошибки - слева оффсет, листании свайпом с тачпада. Например, есть на странице курса "Открытие ритма":

<details>

![image](https://github.com/torin-asakura/drum-in/assets/44067768/baf8a2b2-4f41-4e1e-a767-0a3e21603deb)

</details>

2023-08-11 18:39 UTC, kalininatonya commented
>

2023-08-11 18:43 UTC, kalininatonya commented
> 1. Слайдеры на индексе - ✅
> 2. Конфликты пр - у тебя такая ошибка:
> 
> ```shell
> TypeCheck run failed
> 
> ENOENT: no such file or directory, open '/home/runner/work/drum-in/drum-in/.yarn/virtual/@landing-choose-course-fragment-virtual-761353a221/1/landing/fragments/landing-choose-course/src/slider/desktop-slider/desktop-slider.component.tsx'
> ```
> 
> 3. Поправь размер картинок на этом слайдере, отличаются от дизайна:
> 
> ![image](https://user-images.githubusercontent.com/44067768/259937607-4fc9cc3e-69ce-4df1-8d41-c898f0fff383.png)
> 
> 4. Нашел еще один слайдер для твоих ловких рук - "Как проходит обучение". Те же ошибки - слева оффсет, листании свайпом с тачпада. Например, есть на странице курса "Открытие ритма":
> 
> ![image](https://user-images.githubusercontent.com/44067768/259937278-baf8a2b2-4f41-4e1e-a767-0a3e21603deb.png)

Поправила

2023-08-12 06:40 UTC, Nelfimov approved these changes
👍

2023-08-13 00:50 UTC, TorinAsakura approved these changes
Flawless Victory!

2023-08-13 00:50 UTC, merged