fix: fixed sticky element for locomotive-scroll
torin-asakura/drum-in pull request #113
Opened 2023-08-14 21:29 UTC by kalininatonya

2023-08-15 06:12 UTC, Nelfimov requested changes
1. Ключи полиритмии - ✅
2. Проверь остальные страницы, там такой же баг - напр. Коннакол
3. Пока мы тут, давай дизайн приведем в порядок - в Ключах полиритмии в мобильной версии у прогресса нет черного фона, он прозрачный (https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?type=design&node-id=1904-16739&mode=dev)

2023-08-16 07:37 UTC, Nelfimov requested changes
1. Мобильные локомотивы - ✅
  - В качестве факультатива попробуй уменьшить размер белого блока в мобильном виде - он мерцает при скролле
2. На странице "Ключи полиритмии" в десктопе локомотив не листает до конца, прерывается на полпути:

<details>

<img width="1374" alt="image" src="https://github.com/torin-asakura/drum-in/assets/44067768/08b5a8e9-902a-473c-87c2-a9127f06ba01">

</details>

3. При переходе на некоторые страницы (Открытие ритма) вылетает ошибка, попробуй пофиксить:

<details>

```typescript
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'match')

Source
../../../../.yarn/__virtual__/@forks-react-locomotive-scroll-virtual-238acfd2a1/1/forks/react-locomotive-scroll/src/locomotive-scroll.context.tsx (60:62) @ ResizeObserver.eval

  58 |         })
  59 | 
> 60 |         new ResizeObserver(() => LocomotiveScrollRef.current?.update()).observe(dataScrollContainer)
     |                                                              ^
  61 | 
  62 |         setIsReady(true) // Re-render the context
  63 |       } catch (error) {
```

</details>

2023-08-16 20:41 UTC, kalininatonya commented
- Исправила мерцание белого блока при скролле на мобилках.

> Пока мы тут, давай дизайн приведем в порядок - в Ключах полиритмии в мобильной версии у прогресса нет черного фона, он прозрачный (https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?type=design&node-id=1904-16739&mode=dev)

Тут с беком надо разобраться, немного буду тормозить. Подскажешь мне как там его запустить, где он вообще лежит?https://wp.drumin.pro

2023-08-17 18:28 UTC, kalininatonya commented
> 3.При переходе на некоторые страницы (Открытие ритма) вылетает ошибка, попробуй пофиксить.

Кажется я это пофиксила.

2023-08-17 18:35 UTC, Nelfimov commented
> * Исправила мерцание белого блока при скролле на мобилках.
> 
> > Пока мы тут, давай дизайн приведем в порядок - в Ключах полиритмии в мобильной версии у прогресса нет черного фона, он прозрачный (https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?type=design&node-id=1904-16739&mode=dev)
> 
> Тут с беком надо разобраться, немного буду тормозить. Подскажешь мне как там его запустить, где он вообще лежит?https://wp.drumin.pro

Создал таску для этой проблемы - https://github.com/torin-asakura/drum-in/issues/114

Как решим ее, продолжим работу над этим PR.

2023-08-21 16:38 UTC, kalininatonya commented
> 3. При переходе на некоторые страницы (Открытие ритма) вылетает ошибка, попробуй пофиксить:
Сведения

Глянь, пожалуйста, вроде норм сейчас.

2023-08-22 06:45 UTC, Nelfimov requested changes
> 2. На странице "Ключи полиритмии" в десктопе локомотив не листает до конца, прерывается на полпути:

Не сделано.

> 3. При переходе на некоторые страницы (Открытие ритма) вылетает ошибка, попробуй пофиксить:

✅

2023-08-24 09:17 UTC, Nelfimov commented
Обновил https://github.com/torin-asakura/drum-in/issues/100

На странице "Ключи полиритмии" в мобильном виде новая программа с прозрачным фоном. Надо привести в соответствие с дизайном.

Как получится - поменяю в админке программы у остальных страниц.

2023-08-27 12:42 UTC, kalininatonya commented
> Обновил #100
> 
> На странице "Ключи полиритмии" в мобильном виде новая программа с прозрачным фоном. Надо привести в соответствие с дизайном.
> 
> Как получится - поменяю в админке программы у остальных страниц.

Там же полоса прогресса  - это "белый квадрат", который ездит за картинкой(на заднем плане), а ты вырезал без фона. Надо вырезать с фоном, чтоб я могла спрятать за ним этот квадратик белый. Сможешь?

2023-08-27 17:37 UTC, kalininatonya commented
> 2. На странице "Ключи полиритмии" в десктопе локомотив не листает до конца, прерывается на полпути:

Проверь, пожалуйста, вроде сделала.

2023-08-28 07:31 UTC, Nelfimov commented
> > 3\. На странице "Ключи полиритмии" в десктопе локомотив не листает до конца, прерывается на полпути:
> 
> Проверь, пожалуйста, вроде сделала.

✅

2023-08-28 10:32 UTC, Nelfimov requested changes
Надо проработать решение: https://github.com/torin-asakura/drum-in/issues/115

2023-08-28 12:52 UTC, Nelfimov approved these changes

2023-08-28 16:50 UTC, TorinAsakura approved these changes

2023-08-28 16:50 UTC, merged