fix: changed progressive bar on polyrhythmic-keys-page
torin-asakura/drum-in pull request #116
Opened 2023-09-03 20:35 UTC by kalininatonya

2023-09-04 07:51 UTC, Nelfimov requested changes
Баг с прогрессами при изменении ширины экрана мобильных устройств.

2023-09-04 09:02 UTC, Nelfimov requested changes
Необходим фикс градиентного фона.

2023-10-31 08:07 UTC, absolemDev commented
@Nelfimov, добавил прогресс-бар на странице "Ключи полиритмии". Замечания, предложения?

2023-10-31 09:15 UTC, Nelfimov requested changes
Функционал работает - ок. Код не смотрел.

Сделай пожалуйста аналогично на страницах
- [x] Ощущение времени
- [x] Пятое измерение
- [x] Седьмое небо
- [x] Коннакол

2023-11-01 06:26 UTC, absolemDev commented
Добавил прогресс-бар на всех страницах.

2023-11-01 07:00 UTC, Nelfimov requested changes
По всем `progress-bar.component` замечания одни и те же.

2023-11-01 16:12 UTC, absolemDev commented on landing/entrypoints/renderer/src/pages/_app.tsx
> +import '../public/progress.css'
прописал стили инлайн

2023-11-01 16:13 UTC, absolemDev commented on landing/pages/connacol-page/fragments/landing-program-connacol/src/content-mobile-course/progress-bar.component.tsx
> +      <svg
перенес прогресс-бар в `ui`

2023-11-01 16:14 UTC, absolemDev commented on landing/pages/connacol-page/fragments/landing-program-connacol/src/content-mobile-course/progress-bar.component.tsx
> +          el.style.fill = y - halfHeightWindow <= 0 ? '#f2f2f2' : '#807f7f' // eslint-disable-line no-param-reassign
добавил цвета для прогресс-бара в тему

2023-11-01 16:14 UTC, absolemDev commented on landing/pages/connacol-page/fragments/landing-program-connacol/src/content-mobile-course/progress-bar.component.tsx
> +  useEffect(() => {
логику вынес в хук

2023-11-02 06:55 UTC, Nelfimov requested changes

2023-11-02 06:55 UTC, Nelfimov commented on ui/progress-bar/src/useProgressBar.ts
> +      const heightSvg = 1010
Вынеси рядом в константы

2023-11-02 06:55 UTC, Nelfimov commented on ui/progress-bar/src/useProgressBar.ts
> +        const percentageComplete = ((y - halfHeightWindow) / (heightSvg - 65)) * 100
Все числа в константы с хорошим неймингом

2023-11-02 06:55 UTC, Nelfimov commented on ui/progress-bar/src/progress-bar.tsx
> +interface Props {
Вынеси рядом в progress-bar.interfaces.ts

2023-11-02 08:39 UTC, absolemDev commented on ui/progress-bar/src/useProgressBar.ts
> +      const heightSvg = 1010
Вынес

2023-11-02 08:39 UTC, absolemDev commented on ui/progress-bar/src/useProgressBar.ts
> +        const percentageComplete = ((y - halfHeightWindow) / (heightSvg - 65)) * 100
Поправил нейминг

2023-11-02 08:39 UTC, absolemDev commented on ui/progress-bar/src/progress-bar.tsx
> +interface Props {
Сделал

2023-11-02 09:29 UTC, Nelfimov requested changes

2023-11-02 09:29 UTC, Nelfimov commented on ui/progress-bar/src/use-progress-bar.hook.ts
> +export function useProgressBar(scrollId, progressRef) {
Сохраняем общую стилистику кода - только `const`. Тебе же порядок запуска не важен.

2023-11-02 09:29 UTC, Nelfimov commented on ui/progress-bar/src/use-progress-bar.hook.ts
> +  const heightPath = 945
Имелось в виду перенести константу в соседний файл, напр. `use-progress-bar.constants.ts`. Ну и нейминг неочевиден - из названия необходимо понять что это и куда. Либо JSDoc если совсем сложное описание

2023-11-02 10:31 UTC, absolemDev commented
@Nelfimov, посмотришь или ревью запросить?

2023-11-02 10:33 UTC, Nelfimov commented
У тебя если готово, и я не одобрил - запрашивай у меня. Как я одобрю, сам запрошу дальше у Андрея.

2023-11-02 10:34 UTC, absolemDev commented on ui/progress-bar/src/use-progress-bar.hook.ts
> +export function useProgressBar(scrollId, progressRef) {
Поправил

2023-11-02 10:35 UTC, absolemDev commented on ui/progress-bar/src/use-progress-bar.hook.ts
> +  const heightPath = 945
Исправил

2023-11-02 11:40 UTC, Nelfimov approved these changes
Исправь название на `progress-bar.constants.ts` - сокращения не нужны.

И запрашивай далее у Андрея

2023-11-02 20:08 UTC, TorinAsakura requested changes

2023-11-02 20:08 UTC, TorinAsakura commented on ui/progress-bar/src/progress-bar.component.tsx
> +  const progressRef = useRef(null)
что за null?

2023-11-02 20:08 UTC, TorinAsakura commented on ui/progress-bar/src/progress-bar.constants.ts
> +export const HEIGHT_PATH_OF_PROGRESS_BAR_SVG = 945
если константа одна - её можно вынести наверх компонента

2023-11-02 20:08 UTC, TorinAsakura commented on ui/progress-bar/src/use-progress-bar.hook.ts
> +import { useEffect }                       from 'react'
1. **Оптимизация:** renderProgress вызывается при каждом событии прокрутки, память будет вытекать однозначно, попробуй юзать requestAnimationFrame для оптимизации апдейта стилей

2. **Очистка обработчика:** Не вижу, чтобы ты удалял обработчик события прокрутки при анмаунте компонента

3. **Зависимости useEffect:** В списке зависимостей useEffect есть colors, который, является объектом. Если этот объект создается на каждом рендере, это может привести к избыточным вызовам эффекта

4. **Использование `getBoundingClientRect`:** Этот метод довольно дорогостоящий с точки зрения производительности, особенно при частом вызове. Я бы не стал им злоупотреблять.

5. **Инлайн стили:** Ты применяешь стили напрямую к элементам через style, в данном случае дешевле использовать классы

2023-11-06 18:05 UTC, TorinAsakura approved these changes

2023-11-06 18:07 UTC, merged

2023-11-07 04:17 UTC, absolemDev commented
@Nelfimov, почему закрыли? Нужны ещё доработки.

2023-11-07 05:09 UTC, Nelfimov commented
Это автоматический флоу - если к задаче есть пр, при одобрении и мерже задача и ветка закрываются. 

Создавай новые если что-то упустил