Hotfix/meta tags
torin-asakura/drum-in pull request #118
Opened 2023-10-25 10:28 UTC by absolemDev

https://github.com/torin-asakura/drum-in/issues/117

2023-10-25 11:15 UTC, absolemDev commented
@Nelfimov, запушил пока только `index-page` и `connacol-page`, посмотри правильно ли я все понял.

2023-10-25 12:06 UTC, Nelfimov requested changes

2023-10-25 12:06 UTC, Nelfimov commented on landing/pages/connacol-page/src/connacol.page.tsx
> +  SEO: any
Давай конкретизируем. Как минимум мы знаем что это `Record<>`

2023-10-25 12:27 UTC, absolemDev commented on landing/entrypoints/renderer/src/pages/index.ts
> +export { default, getServerSideProps } from '@landing/index-page'
@Nelfimov, этот экспорт сейчас локально все ломает:
```
Server Error
Error: Cannot query field "seo" on type "Page".
Cannot query field "translation" on type "Page".
```

2023-10-25 13:35 UTC, Nelfimov commented on landing/entrypoints/renderer/src/pages/index.ts
> +export { default, getServerSideProps } from '@landing/index-page'
SEO для индексной страницы нет, вот ответ по всем имеющимся:

<details>

```graphql
{
  "data": {
    "pages": {
      "edges": [
        {
          "node": {
            "link": "https://wp.drumin.pro/polyrhythmic-keys/",
            "uri": "/polyrhythmic-keys/",
            "title": "Ключи полиритмии"
          }
        },
        {
          "node": {
            "link": "https://wp.drumin.pro/konnakol/",
            "uri": "/konnakol/",
            "title": "Коннакол"
          }
        },
        {
          "node": {
            "link": "https://wp.drumin.pro/contacts/",
            "uri": "/contacts/",
            "title": "Контакты"
          }
        },
        {
          "node": {
            "link": "https://wp.drumin.pro/seventh-heaven/",
            "uri": "/seventh-heaven/",
            "title": "Седьмое небо"
          }
        },
        {
          "node": {
            "link": "https://wp.drumin.pro/fifth-dimension/",
            "uri": "/fifth-dimension/",
            "title": "Пятое измерение"
          }
        },
        {
          "node": {
            "link": "https://wp.drumin.pro/a-sense-of-time/",
            "uri": "/a-sense-of-time/",
            "title": "Ощущение времени"
          }
        },
        {
          "node": {
            "link": "https://wp.drumin.pro/discovering-the-rhythm/",
            "uri": "/discovering-the-rhythm/",
            "title": "Открытие ритма"
          }
        },
        {
          "node": {
            "link": "https://wp.drumin.pro/shkola-ritma-mariny-chuprikovoj/",
            "uri": "/shkola-ritma-mariny-chuprikovoj/",
            "title": "Школа ритма Марины Чуприковой"
          }
        },
        {
          "node": {
            "link": "https://wp.drumin.pro/sample-page/",
            "uri": "/sample-page/",
            "title": "Пример страницы"
          }
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```

</details>

2023-10-25 13:38 UTC, Nelfimov commented on landing/entrypoints/renderer/src/pages/index.ts
> +export { default, getServerSideProps } from '@landing/index-page'
Опубликовал, URL: `/home`

2023-10-25 17:15 UTC, absolemDev commented on landing/pages/connacol-page/src/connacol.page.tsx
> +  SEO: any
Расписал типы

2023-10-25 17:19 UTC, absolemDev commented on landing/entrypoints/renderer/src/pages/index.ts
> +export { default, getServerSideProps } from '@landing/index-page'
Другие страницы тоже ломаются. Или я чего-то не понимаю?!

2023-10-25 19:28 UTC, Nelfimov commented on landing/entrypoints/renderer/src/pages/index.ts
> +export { default, getServerSideProps } from '@landing/index-page'
Какие страницы? Что ломается? Теги в деве есть?

2023-10-26 04:12 UTC, absolemDev commented on landing/entrypoints/renderer/src/pages/index.ts
> +export { default, getServerSideProps } from '@landing/index-page'
Везде где я экспортирую ` getServerSideProps` получаю ответ: 
```
Server Error
Error: Cannot query field "seo" on type "Page".
Cannot query field "translation" on type "Page".
```

2023-10-26 05:11 UTC, absolemDev commented on landing/entrypoints/renderer/src/pages/index.ts
> +export { default, getServerSideProps } from '@landing/index-page'
@Nelfimov, куда капнуть можно?

2023-10-26 05:37 UTC, absolemDev commented on landing/entrypoints/renderer/src/pages/index.ts
> +export { default, getServerSideProps } from '@landing/index-page'
@Nelfimov, запросы улетают на `localhost`:
```
Request URL: http://localhost:3000/polyrhythmic-keys
```

2023-10-26 06:39 UTC, Nelfimov commented on landing/entrypoints/renderer/src/pages/index.ts
> +export { default, getServerSideProps } from '@landing/index-page'
Проверь почему так, у нас УРЛ для получения данных такой: https://github.com/torin-asakura/drum-in/blob/0c6c51bff44aebad1a1e6b05ca161bf59f895cba/globals/data/src/helpers/get-client.helper.ts#L6

Все через глобальный аполло клиент.

2023-10-26 06:49 UTC, Nelfimov requested changes
Необходимо поправить ошибку фетчинга данных.

2023-10-26 11:14 UTC, absolemDev commented
@Nelfimov, запрос не отрабатывает:
```
export const GET_INDEX_SEO = gql`
  query GetIndexSeo {
    pageBy(uri: "/home") {
      seo {
        title
        metaDesc
      }
    }
  }
```

2023-10-26 13:08 UTC, Nelfimov commented
Косяк был в админке, SEO не раздавались через graphql.

Все подключил и настроил, теперь доступно. Запрос такой:

<details>

```graphql
query MyQuery {
  allPagesContent {
    nodes {
      seo {
        canonical
        cornerstone
        focuskw
        fullHead
        metaDesc
        metaKeywords
        metaRobotsNofollow
        metaRobotsNoindex
        opengraphAuthor
        opengraphDescription
        opengraphModifiedTime
        opengraphPublishedTime
        opengraphPublisher
        opengraphSiteName
        opengraphTitle
        opengraphType
        opengraphUrl
        readingTime
        title
        twitterDescription
        twitterTitle
      }
      uri
    }
  }
}
```

</details>

Вот все URI:

<details>

```graphql

{
  "data": {
    "allPagesContent": {
      "nodes": [
        {
          "uri": "/pages_content/oferta/"
        },
        {
          "uri": "/pages_content/privacy-policy/"
        },
        {
          "uri": "/pages_content/contacts/"
        },
        {
          "uri": "/pages_content/polyrhythmic-keys/"
        },
        {
          "uri": "/pages_content/konnakol/"
        },
        {
          "uri": "/pages_content/seventh-heaven/"
        },
        {
          "uri": "/pages_content/a-sense-of-time/"
        },
        {
          "uri": "/pages_content/common-fragments/"
        },
        {
          "uri": "/pages_content/fifth-dimension/"
        },
        {
          "uri": "/pages_content/discovering-the-rhythm/"
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```

</details>

Ну и запрос по URI теперь такой:

<details>

```graphql
query MyQuery {
  pageContentBy(uri: "/home") {
    seo {
      canonical
      cornerstone
      focuskw
      fullHead
      metaDesc
      metaKeywords
      metaRobotsNofollow
      metaRobotsNoindex
      opengraphAuthor
      opengraphDescription
      opengraphModifiedTime
      opengraphPublishedTime
      opengraphPublisher
      opengraphSiteName
      opengraphTitle
      opengraphType
      opengraphUrl
      readingTime
      title
      twitterDescription
      twitterTitle
    }
  }
}
```

</details>

2023-10-26 14:10 UTC, absolemDev commented
@Nelfimov, а что с превью, или он здесь не нужен?
```
const GET_PREVIEW = gql`
  query GetPreview($uri: String!) {
    mediaItemBy(uri: $uri) {
      sourceUrl
    }
  }
`
```

2023-10-27 06:30 UTC, absolemDev commented
Сейчас при переходе на `/contacts-page` и `/contract-offer` всплывает ошибка:
```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'match')

Source
../../../../.yarn/__virtual__/@forks-react-locomotive-scroll-virtual-238acfd2a1/1/forks/react-locomotive-scroll/src/locomotive-scroll.context.tsx (62:79) @ ResizeObserver.eval

  60 |         })
  61 | 
> 62 |         resizeObserver = new ResizeObserver(() => LocomotiveScrollRef.current?.update())
     |                                                                               ^
  63 | 
  64 |         if (resizeObserver) {
  65 |           resizeObserver.observe(dataScrollContainer)
```

2023-10-27 06:55 UTC, absolemDev commented
Добавил типизацию пропсов страниц

2023-10-27 06:56 UTC, absolemDev commented
В целом мета теги норм тянутсю

2023-10-27 07:57 UTC, Nelfimov commented
> Сейчас при переходе на `/contacts-page` и `/contract-offer` всплывает ошибка:
> 
> ```
> Unhandled Runtime Error
> TypeError: Cannot read properties of undefined (reading 'match')
> 
> Source
> ../../../../.yarn/__virtual__/@forks-react-locomotive-scroll-virtual-238acfd2a1/1/forks/react-locomotive-scroll/src/locomotive-scroll.context.tsx (62:79) @ ResizeObserver.eval
> 
>   60 |         })
>   61 | 
> > 62 |         resizeObserver = new ResizeObserver(() => LocomotiveScrollRef.current?.update())
>      |                                                                               ^
>   63 | 
>   64 |         if (resizeObserver) {
>   65 |           resizeObserver.observe(dataScrollContainer)
> ```

Проверь нет ли у тебя изменений относительно мастера? И эта ошибка останавливает приложение?

2023-10-27 08:07 UTC, absolemDev commented
> Проверь нет ли у тебя изменений относительно мастера? И эта ошибка останавливает приложение?
* Относительно мастера в locomotiveScroll нет изменений.
* Приложение не останавливается, всплывает модалка с ошибкой

2023-10-27 08:17 UTC, Nelfimov commented
> @Nelfimov, а что с превью, или он здесь не нужен?
> 
> ```
> const GET_PREVIEW = gql`
>   query GetPreview($uri: String!) {
>     mediaItemBy(uri: $uri) {
>       sourceUrl
>     }
>   }
> `
> ```

Превью загрузил - для гугла, фб и твиттера. Можешь проверить?

2023-10-27 08:59 UTC, absolemDev commented
>Превью загрузил - для гугла, фб и твиттера. Можешь проверить?

`null` приходит

2023-10-27 09:03 UTC, absolemDev commented
>`null` приходит

Если по этим `uri`:
```
{
          "uri": "/pages_content/oferta/"
        },
        {
          "uri": "/pages_content/privacy-policy/"
        },
        {
          "uri": "/pages_content/contacts/"
        },
        {
          "uri": "/pages_content/polyrhythmic-keys/"
        },
        {
          "uri": "/pages_content/konnakol/"
        },
        {
          "uri": "/pages_content/seventh-heaven/"
        },
        {
          "uri": "/pages_content/a-sense-of-time/"
        },
        {
          "uri": "/pages_content/common-fragments/"
        },
        {
          "uri": "/pages_content/fifth-dimension/"
        },
        {
          "uri": "/pages_content/discovering-the-rhythm/"
        }
```

2023-10-27 09:55 UTC, absolemDev commented
вытащил `uri` через 
```
opengraphImage {
          uri
        }
```

2023-10-27 10:31 UTC, Nelfimov approved these changes
Делай фикс версии и далее запрашивай ревью у Андрея

2023-10-27 10:31 UTC, Nelfimov commented on landing/pages/contract-offer-page/package.json
> +    "react-helmet": "6.1.0",
Здесь версию верни на `*`

2023-10-27 11:57 UTC, absolemDev commented on landing/pages/contract-offer-page/package.json
> +    "react-helmet": "6.1.0",
поправил

2023-10-27 12:00 UTC, absolemDev commented
@Nelfimov, для превью на всех страниц тянется `uri: '/main-cover/'`. Это норм?

2023-10-27 12:07 UTC, Nelfimov commented
> @Nelfimov, для превью на всех страницах тянется `uri: '/main-cover/'`. Это норм?

Это адрес картинки с превью.

2023-10-27 22:26 UTC, TorinAsakura requested changes

2023-10-27 22:26 UTC, TorinAsakura commented on landing/pages/index-page/src/seo.component.tsx
> +        content: ogCover,
эти данные ты можешь, также, получать по апи, ибо не понятно - что такое ogCover?

2023-10-27 22:26 UTC, TorinAsakura commented on landing/pages/index-page/src/seo.component.tsx
> +        content: '621',
как и размеры

2023-10-30 06:50 UTC, absolemDev commented on landing/pages/index-page/src/seo.component.tsx
> +        content: ogCover,
Поправил

2023-10-30 06:50 UTC, absolemDev commented on landing/pages/index-page/src/seo.component.tsx
> +        content: '621',
Поправил

2023-10-30 07:22 UTC, Nelfimov approved these changes

2023-10-30 14:23 UTC, TorinAsakura requested changes
а если разрешение файла изменится? что тогда?

2023-10-30 14:23 UTC, TorinAsakura commented on landing/pages/connacol-page/src/get-server-side-props.ts
> +    ogImageHeight: '621',
это также можно получать с ендпойнта

2023-10-30 14:37 UTC, absolemDev commented
>ogLocale: 'ru_RU',
    ogImageWidth: '1024',
    ogImageHeight: '621',

>это также можно получать с ендпойнта

@Nelfimov, по каким ендпоинтам можно получить эти данные?

2023-10-31 06:13 UTC, Nelfimov commented
> > ogLocale: 'ru_RU',
> > ogImageWidth: '1024',
> > ogImageHeight: '621',
> 
> > это также можно получать с ендпойнта
> 
> @Nelfimov, по каким ендпоинтам можно получить эти данные?

Добавил ниже запроса:

<details>

```graphql
query MyQuery {
  pageContentBy(uri: "/home") {
    seo {
      canonical
      cornerstone
      focuskw
      fullHead
      metaDesc
      metaKeywords
      metaRobotsNofollow
      metaRobotsNoindex
      opengraphAuthor
      opengraphDescription
      opengraphModifiedTime
      opengraphPublishedTime
      opengraphPublisher
      opengraphSiteName
      opengraphTitle
      opengraphType
      opengraphUrl
      readingTime
      title
      twitterDescription
      twitterTitle
      opengraphImage {
        sizes
        caption
        description
        isPreview
        link
        title
        altText
        desiredSlug
        mediaDetails {
          file
          height
          sizes {
            file
            fileSize
            mimeType
            height
            name
            sourceUrl
            width
          }
          width
        }
      }
    }
  }
}
```

</details>

2023-10-31 10:28 UTC, absolemDev commented
@Nelfimov, а эти данные как можно вытащить?
```
"ogLocale": "ru_RU",
"twitterCard": "summary_large_image"
```

2023-10-31 14:09 UTC, absolemDev commented
Обновил поля запроса, но эти данные так и не тянутся:
```
"ogLocale": "ru_RU",
"twitterCard": "summary_large_image"
```

2023-10-31 18:45 UTC, Nelfimov commented
> Обновил поля запроса, но эти данные так и не тянутся:
> 
> ```
> "ogLocale": "ru_RU",
> "twitterCard": "summary_large_image"
> ```

Давай пока без этого.

2023-11-01 06:30 UTC, absolemDev commented
@Nelfimov, ревью будем запрашивать?

2023-11-01 07:01 UTC, Nelfimov commented
> @Nelfimov, ревью будем запрашивать?

Да

2023-11-02 06:50 UTC, Nelfimov approved these changes

2023-11-02 13:46 UTC, TorinAsakura requested changes
ОЧень раздутые queries, я не смог найти и половины используемых полей оттуда, не считая тех, которые мы используем в seo компонентах

2023-11-02 13:46 UTC, TorinAsakura commented on landing/pages/connacol-page/src/data/queries/seo.query.ts
> +              height
мы все эти данные где-то используем?

2023-11-02 14:59 UTC, absolemDev commented on landing/pages/connacol-page/src/data/queries/seo.query.ts
> +              height
Удалил лишние поля запроса.

2023-11-02 15:00 UTC, absolemDev commented
>ОЧень раздутые queries, я не смог найти и половины используемых полей оттуда, не считая тех, которые мы используем в seo компонентах

Согласен. Удалил лишние поля запроса.

2023-11-02 20:12 UTC, TorinAsakura approved these changes

2023-11-02 20:12 UTC, merged