hotfix/progress-bar
torin-asakura/drum-in pull request #121
Opened 2023-11-07 13:40 UTC by absolemDev

2023-11-08 06:50 UTC, Nelfimov requested changes

2023-11-08 06:50 UTC, Nelfimov commented on ui/progress-bar/src/components/logo-point.component.tsx
> +const LogoPoint = ({ id }) => {
а интерфейс?

2023-11-08 06:50 UTC, Nelfimov commented on ui/progress-bar/src/components/point.component.tsx
> +const Point = ({ id }) => {
интерфейс

2023-11-08 06:50 UTC, Nelfimov commented on ui/progress-bar/src/components/progress-path.component.tsx
> +const ProgressPath = ({ id }) => {
интерфейс

2023-11-08 06:50 UTC, Nelfimov commented on ui/progress-bar/src/components/use-point.hook.ts
> +export const usePoint = (id) => {
интерфейс

2023-11-08 06:50 UTC, Nelfimov commented on ui/progress-bar/src/components/use-point.hook.ts
> +  const [fill, setFill] = useState(theme.colors.progressBar.default)
посмотри `useTheme`

2023-11-08 06:50 UTC, Nelfimov commented on ui/progress-bar/src/components/use-point.hook.ts
> +        rootMargin: '0% 0% -50% 0%',
Это тоже можно из темы вытаскивать

2023-11-08 06:50 UTC, Nelfimov commented on ui/progress-bar/src/components/use-point.hook.ts
> +          setFill(theme.colors.progressBar.progress)
из темы

2023-11-08 06:50 UTC, Nelfimov commented on ui/progress-bar/src/components/use-point.hook.ts
> +          setFill(theme.colors.progressBar.default)
из темы

2023-11-08 06:50 UTC, Nelfimov commented on ui/progress-bar/src/progress-bar.component.tsx
> +    <Box position='absolute' top={0} data-scroll data-scroll-id={`${scrollId}_progress_path`}>
Может это размапить? У тебя повторения с отличиями в значениях. Можно создать объект в `left`, `top` и id.

2023-11-08 06:50 UTC, Nelfimov commented on ui/progress-bar/package.json
> +    "@forks/react-locomotive-scroll": "workspace:0.0.1",
У тебя эта библиотека выше в основных зависимостях. Уверен что здесь нужна? А уверен что она нужна именно в обычных зависимостях?

2023-11-08 10:45 UTC, absolemDev commented on ui/progress-bar/src/components/logo-point.component.tsx
> +const LogoPoint = ({ id }) => {
добавил

2023-11-08 10:45 UTC, absolemDev commented on ui/progress-bar/src/components/point.component.tsx
> +const Point = ({ id }) => {
добавил

2023-11-08 10:45 UTC, absolemDev commented on ui/progress-bar/src/components/progress-path.component.tsx
> +const ProgressPath = ({ id }) => {
добавил

2023-11-08 10:45 UTC, absolemDev commented on ui/progress-bar/src/components/use-point.hook.ts
> +export const usePoint = (id) => {
добавил

2023-11-08 10:46 UTC, absolemDev commented on ui/progress-bar/src/components/use-point.hook.ts
> +  const [fill, setFill] = useState(theme.colors.progressBar.default)
взял тему из useTheme

2023-11-08 10:46 UTC, absolemDev commented on ui/progress-bar/src/components/use-point.hook.ts
> +        rootMargin: '0% 0% -50% 0%',
добавил в тему

2023-11-08 10:47 UTC, absolemDev commented on ui/progress-bar/src/progress-bar.component.tsx
> +    <Box position='absolute' top={0} data-scroll data-scroll-id={`${scrollId}_progress_path`}>
сделал

2023-11-08 10:47 UTC, absolemDev commented on ui/progress-bar/package.json
> +    "@forks/react-locomotive-scroll": "workspace:0.0.1",
поправил

2023-11-08 10:48 UTC, absolemDev commented
Прикрутил еще оптимизации для рендера прогресс-бара, а именно добавил хелпер `thottle`

2023-11-10 15:14 UTC, Nelfimov approved these changes

2023-11-10 22:42 UTC, TorinAsakura requested changes

2023-11-10 22:42 UTC, TorinAsakura commented on ui/progress-bar/src/components/use-progress-path.hook.ts
> +      progressPath!.style.strokeDashoffset = (dashOffset - offsetUnit).toString()
а если элемент будет не найден? используй стандартный null safety, не ленись

2023-11-10 22:42 UTC, TorinAsakura commented on ui/progress-bar/src/components/use-progress-path.hook.ts
> +        ((yoPath - halfHeightWindow) / HEIGHT_PATH_OF_PROGRESS_BAR_SVG) * 100
если HEIGHT_PATH_OF_PROGRESS_BAR_SVG может изменится его тоже лучше включить в зависимости

2023-11-10 22:42 UTC, TorinAsakura commented on ui/progress-bar/src/helpers/throttle.ts
> +export const throttle = (func: Function, ms: number) => {
лучше (…args: any[]) => void, если тут нет возвращаемого значения

2023-11-10 22:42 UTC, TorinAsakura commented on ui/progress-bar/src/helpers/throttle.ts
> +      func.apply(this, args)
ты же помнишь, что в стрелочных функциях this не биндится? тут может начаться размыв контекста

2023-11-10 22:42 UTC, TorinAsakura commented on ui/progress-bar/src/helpers/throttle.ts
> +    setTimeout(() => {
не вижу очистки таймера по выполнении

2023-11-13 06:14 UTC, absolemDev commented on ui/progress-bar/src/components/use-progress-path.hook.ts
> +      progressPath!.style.strokeDashoffset = (dashOffset - offsetUnit).toString()
Добавил null safety, так же вынес в переменную функцию очистки скрола

2023-11-13 06:25 UTC, absolemDev commented on ui/progress-bar/src/components/use-progress-path.hook.ts
> +        ((yoPath - halfHeightWindow) / HEIGHT_PATH_OF_PROGRESS_BAR_SVG) * 100
`HEIGHT_PATH_OF_PROGRESS_BAR_SVG` константа, при добавлении её в зависимости useEffect `yarn check` ругается что изменение `HEIGHT_PATH_OF_PROGRESS_BAR_SVG` не приведет к ререндеру.

2023-11-13 06:26 UTC, absolemDev commented on ui/progress-bar/src/helpers/throttle.ts
> +      func.apply(this, args)
Согласен, привязка к `this` в данном случае излишня

2023-11-13 06:26 UTC, absolemDev commented on ui/progress-bar/src/helpers/throttle.ts
> +    setTimeout(() => {
Поправил

2023-11-13 07:31 UTC, Nelfimov requested changes

2023-11-13 07:31 UTC, Nelfimov commented on ui/progress-bar/src/components/use-point.hook.ts
> +  const theme: any = useTheme()
Ну как же `any` - `useTheme` тебе возвращает конкретный интерфейс же

2023-11-13 08:23 UTC, absolemDev commented on ui/progress-bar/src/components/use-point.hook.ts
> +  const theme: any = useTheme()
сделал по подобию https://github.com/torin-asakura/drum-in/blob/8987d0bf43641d6ce3779a0ca0374277c1824a2d/ui/icons/src/PopIcon.tsx#L9
не нашел что бы в теме были интерфейсы прописаны.

2023-11-13 08:33 UTC, Nelfimov commented on ui/progress-bar/src/components/use-point.hook.ts
> +  const theme: any = useTheme()
Посмотри какой интерфейс возвращает `useTheme`. Ты взял пример из иконок, а там такое автоматом генерируется.

2023-11-13 09:13 UTC, absolemDev commented on ui/progress-bar/src/components/use-point.hook.ts
> +  const theme: any = useTheme()
если я не указываю `any` тогда `yarn check` выдает ошибку когда хочу получить доступ к `theme.colors.progressBar.progress` или `theme.margins.rootMargin`
```
Error: Property 'colors' does not exist on type 'Theme'.
---
Error: Property 'margins' does not exist on type 'Theme'.
```

2023-11-13 10:14 UTC, Nelfimov commented on ui/progress-bar/src/components/use-point.hook.ts
> +  const theme: any = useTheme()
тогда оставляй `any` и перезапрашивай ревью

2023-11-13 11:27 UTC, Nelfimov approved these changes

2023-11-13 12:25 UTC, TorinAsakura approved these changes

2023-11-13 12:25 UTC, merged