refactor: general fragments wp data
torin-asakura/drum-in pull request #148
Opened 2024-03-28 22:50 UTC by oksssvv

2024-03-29 05:08 UTC, Nelfimov requested changes
проверь баг с блоком учителя - при листании вправо пропадает последний элемент


https://github.com/torin-asakura/drum-in/assets/44067768/439b852f-220a-459f-8aaa-5c870cec5d43

2024-03-29 10:42 UTC, Nelfimov requested changes
а теперь пропал скролл блока учителя свайпом в сторону на тачпаде

2024-03-29 12:26 UTC, oksssvv commented
@Nelfimov 

> а теперь пропал скролл блока учителя свайпом в сторону на тачпаде

а слайдеры точно нормально работали (вопрос больше к тач устройствам)? потому что я сейчас пытаюсь хоть как то привести в чувства слайдер на мобайл версии - он ведет себя совершенно непокорно, что бы я не делала

т.к. данные я получила для слайдера, возможно целесообразнее эти корректировки вводить в отдельной задаче?

2024-03-29 20:40 UTC, oksssvv commented
@Nelfimov 

>а теперь пропал скролл блока учителя свайпом в сторону на тачпаде

Может быть что то с эмулятором, т.к. у меня не всегда срабатывает, записала наглядное видео, по сути все работает на устройствах:
- стандарный вьюпорт
- мобайл
- 1440
- ipad air

<details>

[recording.webm](https://github.com/torin-asakura/drum-in/assets/126156026/70238a84-f1b9-4b0e-a252-4e5a5c9687e9)

</details>

или я не на то обратила внимание? если ты имел другое ввиду - скажи поконкретнее как протестить

2024-03-30 08:14 UTC, Nelfimov commented
@oksssvv залил тебе фикс.

Как это можно было подебажить?

На странице открытия ритма есть такой слайдер:

<img width="1380" alt="image" src="https://github.com/torin-asakura/drum-in/assets/44067768/8196ad10-000f-4670-8199-2402281594ee">

У него все работает - свайпом по горизонтали все листается.

То что ты пробовала - это тач. Тач работал и так. А нужно было добавить горизонтальный скролл. На маке это два пальца в сторону при ховере на элементе.

2024-03-30 13:26 UTC, Nelfimov approved these changes
необходимо проверить получение песни

2024-03-30 13:26 UTC, merged