feat(skills-to-learn-fragment): markup moved to components
torin-asakura/drum-in pull request #15
Opened 2021-12-02 18:51 UTC by gochicus

2021-12-03 15:56 UTC, TFK70 requested changes

2021-12-03 15:56 UTC, TFK70 commented on site/skills-to-learn-fragment/src/image-block/image-block.interface.tsx
>    zIndex?: string | number | string[] | number[]
Почему они тут? Ты же должен был их убрать

2021-12-03 15:56 UTC, TFK70 commented on site/skills-to-learn-fragment/src/image-block/image-block.interface.tsx
> +  style?: {}
Что это?

2021-12-03 15:56 UTC, TFK70 commented on site/skills-to-learn-fragment/src/text-block/item.component.tsx
> +const Item: FC<TextBlockProps> = ({ display }) => (
Убери display из пропсов, так делать не надо. Регулируй это контейнером

2021-12-03 16:00 UTC, gochicus commented on site/skills-to-learn-fragment/src/image-block/image-block.interface.tsx
> +  style?: {}
@TFK70  задаю границу компонента инлайн-стилем, но он не проходит typecheck  ,без внесения в интерфейс.

2021-12-03 16:14 UTC, TFK70 requested changes
-  
![image](https://user-images.githubusercontent.com/62806448/144634323-e6604f36-0ee4-4c3f-a7e9-6b7850097232.png)

Переименовать директорию в item, переименовать интерфейс в ItemProps
- > Причем внутри фрагмента все должно быть разбито на сущности именно таким образом, для того чтобы в будущем можно было без проблем поменять разметку

?
1. Сделать сущность Skills, в которой будут мапиться скиллы
2. Внутри Skills сделать Item (это вместо  твоего ListItem)
3. Убрать контейнеры для красной ленточки, пока просто забудь что она существует
4. Упорядочить разметку по этим сущностям, как и было указано в задаче
5. Убрать компонент SliderControls (что это вообще?)

- Выполнить 3 пункт задачи

> Удалить пропсы: width, height, position, zIndex

2021-12-03 17:56 UTC, TFK70 requested changes

2021-12-03 17:56 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.component.tsx
> +        <Layout flexBasis={['11px', '11px', '18px']} />
Почему это дублируется?

2021-12-03 17:56 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.interface.ts
> +    skills: any
items*

2021-12-03 17:56 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.interface.ts
> +    skills: any
И да, во-первых это `any[]`, во-вторых повесь `TODO strict type`, чтобы в будущем здесь нормальный тип указали на этапе работы с данными

2021-12-03 17:56 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.component.tsx
> +import { Item }   from '../item'
Item должен быть внутри директории skills

2021-12-06 09:48 UTC, TFK70 approved these changes

2021-12-06 14:04 UTC, TorinAsakura approved these changes

2021-12-06 14:04 UTC, merged