refactor: main page wp data
torin-asakura/drum-in pull request #150
Opened 2024-03-29 20:19 UTC by oksssvv

- hero
- runningLine
- chooseCourse
- individualLesson
- slider
- students
- background

2024-03-30 13:31 UTC, Nelfimov requested changes
1. конфликты
2. необходимо провести рефактор админки - у тебя в записи "Общие фрагменты" абсолютно все - и учитель, и выбор курса, и главная, и контракты. Надо было в _блоке_ "Общие фрагменты" делать отдельные записи - FAQ, Учитель и т.д. А у тебя вышел монолитище.

2024-04-01 12:10 UTC, oksssvv commented
@Nelfimov 

> Надо было в блоке "Общие фрагменты" делать отдельные записи - FAQ, Учитель и т.д.

подскажи как оформить эти записи? я добавила `Контакты` к `Общим фрагментам`, теперь запись тут отображается, но как ее довести до AFC, чтобы далее пересоздать поля, заполнить их и получить через gql? 

![Снимок экрана от 2024-04-01 15-06-43](https://github.com/torin-asakura/drum-in/assets/126156026/9c4a7e55-146e-4dbb-870d-93d5c0227370)

2024-04-01 12:14 UTC, Nelfimov commented
Посмотри как сделан "Курс":

<img width="1335" alt="image" src="https://github.com/torin-asakura/drum-in/assets/44067768/978ec37b-4fe8-473c-b306-16bbc0b5d2f3">

Тебе нужно соответственно сделать ссылку не на Тип записи, а на Запись. Предварительно создав эту запись.

Алгоритм будет такой:
 1. создать новую запись в Общие фрагменты
 2. создать новый тип записи в ACF
 3. добавить правило местонахождения как описал выше
 4. отредактировать ACF как нужно 
 5. добавить настройки graphql

2024-04-01 13:03 UTC, oksssvv commented
@Nelfimov 
создала тип в afc, сделала группу послей с  этим типом (Контакты)

В итоге это отдельная вкладка в ВП сейчас, а не подраздел общих фрагментов, ты вроде бы как говорил делать все в общих

по такой схеме будут получаться отдельные типы с отдельными полями в afc, а также под каждый будет отдельная вкладка (в левом сайдбаре WP), ну и равно что они не будут относится к общим фрагментам, как ты ранее советовал

2024-04-01 13:17 UTC, Nelfimov commented
Посмотри в сторону переноса в "Тип записи" ACF

https://wp.drumin.pro/wp-admin/edit.php?post_type=acf-post-type

2024-04-01 19:21 UTC, oksssvv commented
@Nelfimov 
подскажи по какой причине может быть такое дублирование полей, я так поняла сколько записей в Общих фрагментах столько и дубляжей, как это избежать? я получаю переизбыток данных

gql IDE: 

<details>

![Снимок экрана от 2024-04-01 22-20-21](https://github.com/torin-asakura/drum-in/assets/126156026/b0a03fa7-f9c1-461f-82ae-89cdcab4197f)
</details>

сделала тестовый запрос контактов в коде, такая же картина:

<details>

![Снимок экрана от 2024-04-01 22-18-47](https://github.com/torin-asakura/drum-in/assets/126156026/340ee9c2-f1db-40e9-b753-f49af7f53c0a)
</details>

2024-04-02 06:33 UTC, Nelfimov commented
внеси данные в другую группу полей из "общие фрагменты", напр. в договоре оферты.

Такое впечатление что раз остальные группы пустые, то тянется contacts

2024-04-02 07:16 UTC, Nelfimov commented
Делай квери с запросом по ID к ноде

2024-04-03 09:16 UTC, Nelfimov approved these changes

2024-04-03 09:16 UTC, merged