refactor(opening-rhythm): layout
torin-asakura/drum-in pull request #155
Opened 2024-04-05 13:46 UTC by oksssvv

- дозаполнены поля wp
- подкорректированна разметка 
- отображение данных в модалке оплаты

2024-04-05 14:26 UTC, Nelfimov requested changes
<img width="1370" alt="Screenshot 2024-04-05 at 17 25 33" src="https://github.com/torin-asakura/drum-in/assets/44067768/282decb6-46dc-4cbe-b6d5-cb7ef9b5c2e7">
<img width="1370" alt="Screenshot 2024-04-05 at 17 25 48" src="https://github.com/torin-asakura/drum-in/assets/44067768/f4d7a6eb-bb0b-471c-aa84-2c1a0e5bb6e5">

2024-04-05 15:42 UTC, oksssvv commented
@Nelfimov 

по поводу превого скрина ^ , как это должно выглядеть? расстановка элементов в контейнере по дизайну есть только для десктопа и мобайла, нужно выставить контейнер в центр? или на скрине вопросы только к заголовку? 
как вариант можно заменить на картинку конечно, и растягивать как хочется на брейкпоинтах

2024-04-08 11:18 UTC, oksssvv commented
@Nelfimov 

> не видно других слайдов

учитель - это общий фрагмент, я его изменю в ветке https://github.com/torin-asakura/drum-in/pull/157


>что делают иконки в корне проекта?

svg изменяла, сейчас уберу

2024-04-08 11:36 UTC, Nelfimov approved these changes

2024-04-08 11:36 UTC, merged