refactor(individual-courses): layout
torin-asakura/drum-in pull request #156
Opened 2024-04-05 13:49 UTC by oksssvv

- дополнены данные wp 
- доработано содержание для модалки Оплаты
- подкоректированна верстка

2024-04-05 14:32 UTC, Nelfimov requested changes
Поздно начинает идти белая полоска прогресса

<img width="1370" alt="image" src="https://github.com/torin-asakura/drum-in/assets/44067768/87fbae90-17ce-4baf-99e4-e41b42c69c31">

Не видны границы слайдера - непонятно что есть еще фото. На дизайне видны куски следующих слайдов

<img width="1370" alt="Screenshot 2024-04-05 at 17 30 03" src="https://github.com/torin-asakura/drum-in/assets/44067768/e74017fb-69ec-40f0-b8cc-3a68ec46ac23">

Размер шрифтов некорректный 

<img width="1370" alt="Screenshot 2024-04-05 at 17 30 11" src="https://github.com/torin-asakura/drum-in/assets/44067768/7c355459-6f74-446f-b53d-f9799761544c">

2024-04-05 16:47 UTC, oksssvv commented
@Nelfimov 

> Размер шрифтов некорректный

нашла несоответсвие только у `₽/мес`, 18 вместо 20, но остальные по дизайну совпадают с оформлением мобильной версии

> Не видны границы слайдера - непонятно что есть еще фото. На дизайне видны куски следующих слайдов

это общий фрагмент, изменю в другой ветке

2024-04-08 11:11 UTC, Nelfimov requested changes
1. не видны слайды боковые

<img width="1363" alt="image" src="https://github.com/torin-asakura/drum-in/assets/44067768/eeacf193-f492-40ad-8446-cb572bed34aa">

2024-04-08 11:19 UTC, oksssvv commented
@Nelfimov 

> не видны слайды боковые

учитель - это общий фрагмент, я его изменю в следующей ветке

2024-04-08 13:36 UTC, Nelfimov approved these changes

2024-04-08 13:37 UTC, merged