refactor: getting-id-for-terminal
torin-asakura/drum-in pull request #178
Opened 2024-05-02 10:46 UTC by oksssvv

- создание записи и полей в wp Настройки сайта / Настройки оплаты
- удаление ID для тинькофф терминала в коде
- получение Настроек оплаты при помощи ssg + isr для всех страниц
- передача storeID в form-payment из всех использующих его модальных окон оплаты

2024-05-03 05:26 UTC, Nelfimov requested changes
Пришла пора провести рефактор:

apollo с его кэшем позволяет вытаскивать данные в любом месте приложение без "пробрасывания" пропсов. Это значит что ты можешь:
- в `getStaticProps` получить данные на сервере
- не передавать их в `return`
- по необходимости получать их по хуку в любом месте приложения, и это не будет провоцировать новый запрос на клиенте т.к. уже есть в кэше. Важно использовать один и тот же `query` для операций на сервере и клиенте.

У нас так построена вся дельта по сути.

2024-05-03 07:47 UTC, oksssvv commented
@Nelfimov 

>Пришла пора провести рефактор:

сейчас это реализовать только касаемо получения id tinkoff terminal (в рамках этого пр)? 

то есть я getStaticProps оставляю как он есть, из return убираю paymentSettingsData, зачищаю цепочку пропсов

затем создаю хук с точно таким же получением данных, используя уже готовый кверь
```typescript
  const { data: paymentSettingsContent } = await client.query({
    query: GET_PAYMENT_SETTINGS,
    variables: { id: GeneralFragmentID.SETTINGS },
  })
```
и просто использую там где нужно (передаю пропсом в ui/form)?

больше никаких действий не требуется?

2024-05-03 08:11 UTC, Nelfimov commented
@oksssvv да.

`getServerSideProps` точно работает. Думаю и с статикой аналогично будет.

2024-05-03 16:28 UTC, oksssvv commented
@Nelfimov 

провела небольшой тест

в одной странице сделала как ты сказал, вместо передачи через пропсы я добавила хук для получения storeID, запустила билд + старт, зашла в WP и снесла storeID, мое ожидание было что сайт не должен об этом знать, т.к. ревалидации не было (если предположительно запрос должен был идти из кэша), но я получила ошибку о некоректном ID, затем добавила storeID обратно и опять же данные обновились без ревалидации

в моем понимании это значит что запрос был сделан как обычно, кэшированными данными он не воспользовался

вопрос:
значит ли это что такой метод не работает с SSG?

2024-05-03 18:05 UTC, Nelfimov commented
Проверь в режиме дебага что происходит:
- приходит ли ответ на квери на сервере
- Сохраняется ли он в кэше
- Отличается ли запрос на клиенте от запроса на сервере

Все это - в режиме дев

2024-05-06 15:07 UTC, Nelfimov commented
> т.к. get static используется на сервере в нем нельзя использовать хуки, что бы например воспользоваться общим контекстом и вынуть кэш для получения storeID в дочерних компонентах

Верно.

> например, есть страница коннакол, в ее getStaticProps я создаю новый экземпляр клиента (const client = getClient()) и через него делаю все запросы

Попробуй использовать `useApollo` - он сидит у тебя в `_app`. В нем есть функционал хранения кэша.

Я тебе предлагаю пройтись дебагом - поставить брейкпоинт на выполнение какого либо квери _на клиенте_ и посмотреть что есть в объекте кэша.

2024-05-06 18:08 UTC, oksssvv commented
@Nelfimov 

если дело в объеме пропсов, то могу ли я заменить это на получение из кэша? таким методом :

```typescript
import { useApolloClient }      from '@apollo/client'

export const usePaymentStoreID = () => {
  const client = useApolloClient()
  const storeID = client.cache.extract().paymentSettingsData.storeID

  return {storeID}
}
}

```
данный хук я могу использовать в компоненте который передает в форму storeID, таким же образом я могу получать все остальные данные для фрагментов в страницах

это решает проблему переизбытка пропсов на странице и дочерних компонентах, также в данном случае мы получаем данные из кэша который был получен в getStaticProps

2024-05-06 23:52 UTC, oksssvv commented
@Nelfimov 

посмотри пожалуйста последнее состояние ветки, я выполнила указания на странице `polyrhythmic-keys`, использовала клиент от `initializeApollo`, а также добавление данных в `addApolloState`, пока оставила только 4 пропса для страницы (т.к. они используются непосредственно прямо в ней)

состояние данных тестировала, в хуках расставила `cache-only`, при изменение полей в WP данные полученные из хуков не меняются, только после ревалидации

дай обратную связь все ли верно выполнено, если да то сделаю также на всех страницах

2024-05-07 06:12 UTC, Nelfimov commented
@oksssvv подход верный, только используй `useApollo` - он содержит в себе `initializeApollo`

2024-05-07 09:27 UTC, oksssvv commented
@Nelfimov 

>только используй useApollo - он содержит в себе initializeApollo

там используется useMemo, а getStaticProps это ж обычная функция, не будет работать оптимизация, я сделала так: 

```typescript

// используется в app
export const useApollo: UseApollo = (pageProps) => {
  const state = pageProps[APOLLO_STATE_PROP_NAME]
  return useMemo(() => initializeApollo({ initialState: state }), [state])
}

// будет использоваться во всех getStaticProps
export const useApolloOnServer: UseApollo = (pageProps) => {
  const state = pageProps[APOLLO_STATE_PROP_NAME]
  return initializeApollo({ initialState: state })
}

```

просто положу их рядом, нормальный вариант?

2024-05-07 09:28 UTC, Nelfimov commented
> просто положу их рядом, нормальный вариант?

ok

2024-05-08 05:24 UTC, Nelfimov approved these changes

2024-05-08 05:24 UTC, merged