Feature/apply styles
torin-asakura/drum-in pull request #27
Opened 2021-12-07 16:57 UTC by gochicus

#26

2021-12-08 15:23 UTC, TFK70 requested changes

2021-12-08 15:23 UTC, TFK70 commented on site/app/src/pages/_app.tsx
> +  <IntlProvider locale='ru'>
Что это и зачем?

2021-12-08 15:23 UTC, TFK70 commented on site/index-page/src/index-page.tsx
> +  <IntlProvider locale='ru'>
???

2021-12-10 12:26 UTC, TFK70 commented on site/index-page/src/index-page.tsx
> +  <IntlProvider locale='ru'>
@gochicus ты это не убрал?

2021-12-10 12:43 UTC, TFK70 requested changes

2021-12-10 12:43 UTC, TFK70 commented on site/app/src/pages/_app.tsx
> +
вайтспейс

2021-12-10 12:43 UTC, TFK70 commented on site/course-description-fragment/src/course-description.component.tsx
> +                  {' '}
А можно вообще узнать назначение этих пробелов? Они тут не случайно?

2021-12-10 12:43 UTC, TFK70 commented on site/footer/src/messages.ts
> +    defaultMessage: '+7-926-246-47-59',
Ну вообще такие данные тоже идут с бека
Если у человека телефон поменяется - ему придется в код лезть?

2021-12-10 12:43 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +          position={['absolute', 'absolute', 'relative']}
Абсолюты? Зачем?

2021-12-10 12:43 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +          zIndex={[-1, -1, 0]}
И это?

2021-12-10 12:43 UTC, TFK70 commented on site/header-fragment/src/navigation/navigation.component.tsx
> +      position='absolute'
Почему у навигейшена абсолют? Где ты такое увидел?

2021-12-10 12:43 UTC, TFK70 commented on site/header-fragment/src/navigation/navigation.component.tsx
> +      position='absolute'
У нас же лендинг строится по этому принципу: каждый блок будто друг на друге стоит, а ты самый верхний из них просто вырываешь их потока

2021-12-10 12:43 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <Layout flexBasis={520} />
Почему у тебя лейауты дублируются?

2021-12-10 12:43 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +      <ImageBlock />
Где контейнеры?

2021-12-10 12:43 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/item/item.interface.ts
> +  main: any
any?  И что за main?

2021-12-10 12:43 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/item/list.component.tsx
> +const List = ({ main }) => (main !== null ? main.map((item) => <Layout>{item}</Layout>) : null)
У тебя мейн никогда не будет нуллом. Если его нет - его тип undefined. В любом случае тебя не устраивает ни нулл, ни андефайнд, так что просто проверяй его на falsy. `!main`

2021-12-10 12:43 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/item/list.component.tsx
> +const List = ({ main }) => (main !== null ? main.map((item) => <Layout>{item}</Layout>) : null)
Ну с учетом предыдущего коммента про название переменной, я до сих пор без понятия что там лежит

2021-12-10 12:43 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.component.tsx
> +            <Item header={item !== null ? item[0] : null} main={item !== null ? item[1] : null} />
Снова жуткие тернарники в верстке? Что они делают?

2021-12-10 12:43 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.component.tsx
> +  items !== null
Почему нулл?

2021-12-10 12:43 UTC, TFK70 commented on ui/button/src/styles/appearance/abstract/primary-colors.styles.ts
> +    borderColor: 'red',
Выглядит как халтура. Почему цвет не из темы?

2021-12-10 12:43 UTC, TFK70 commented on ui/theme/src/theme/fontSizes.ts
> +  small: '13px',
Почему стринги? У нас же везде numberом они описываются

2021-12-10 12:43 UTC, TFK70 commented on ui/input/src/input.styles.ts
> +export const borderBottomStyles = {
Что это?

2021-12-10 13:11 UTC, gochicus commented on site/index-page/src/index-page.tsx
> +  <IntlProvider locale='ru'>
@TFK70 нет, у меня пока только так intl работает.  Позже попробую поменять.

2021-12-10 13:12 UTC, gochicus commented on site/course-description-fragment/src/course-description.component.tsx
> +                  {' '}
@TFK70 результат команды формат, я их стараюсь руками убирать, но пропускаю видимо.

2021-12-10 13:13 UTC, TFK70 commented on site/index-page/src/index-page.tsx
> +  <IntlProvider locale='ru'>
@gochicus почему ты не сказал-то ничего про это? Еще и коммент проигнорил
Как зафиксируешься сделай коммит где ошибка воспроизводится и пингани меня

2021-12-10 13:14 UTC, gochicus commented on site/header-fragment/src/header.component.tsx
> +          position={['absolute', 'absolute', 'relative']}
@TFK70 красная полоса: в хэдере 
https://www.figma.com/file/ayVC8CGn4jPeDXlkKKXjUX/Untitled?node-id=183%3A9

2021-12-10 13:14 UTC, TFK70 commented on site/course-description-fragment/src/course-description.component.tsx
> +                  {' '}
это результат твоих
```javascript
<Text> Text </Text>
```

Формат все правильно делает

2021-12-10 13:15 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +          position={['absolute', 'absolute', 'relative']}
@gochicus которую я тебе сказал не делать

2021-12-10 13:17 UTC, gochicus commented on site/header-fragment/src/header.component.tsx
> +          position={['absolute', 'absolute', 'relative']}
@TFK70 да, в бэкбоуне, ты сказал что код только путают.  Мне её вообще что-ли не делать?  В макете-то она есть.

2021-12-10 13:19 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +          position={['absolute', 'absolute', 'relative']}
А тут не путают? Ты же абсолютно то же самое написал, ты не должен был ее вообще самостоятельно делать

2021-12-10 13:23 UTC, gochicus commented on ui/button/src/styles/appearance/abstract/primary-colors.styles.ts
> +    borderColor: 'red',
@TFK70  потому-что это драфт,  не законченная работа,  а начинал я с тестирования, что то, что я делаю просто работает. На этапе инициализации кнопки темы просто не было. У инпута, например, поле для ввода зеленого цвета, просто ради теста, сам инпут я ещё нигде не использовал.

2021-12-10 13:25 UTC, gochicus commented on site/header-fragment/src/header.component.tsx
> +          position={['absolute', 'absolute', 'relative']}
@TFK70  то, что её не нужно делать вообще ты не писал. Только то, что в бэкбоуне абсолюты всё путают.

2021-12-10 13:44 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills/skills.component.tsx
> +  items !== null
@TFK70 в моках так обозначил отсутствие второго массива.  Skills нужно переписать будет, так что это, вероятно, тоже уйдет.

2021-12-10 14:01 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.component.tsx
> +  items !== null
@gochicus нет, "вероятно уйдет, вероятно не уйдет" - так не пойдет. Это хаос. Мы же вроде договаривались что ты работаешь последовательно. Если ты в чем-то не уверен - ты должен обратиться за помощью. 

> Skills нужно переписать будет

Что в нем переписывать и зачем?

2021-12-10 14:12 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills/skills.component.tsx
> +  items !== null
@TFK70 Компонент получился негибким, в случае если в данных вместо двух и более массивов, вложенных в массив  items,  есть только один, то блок, включая:
https://www.figma.com/file/ayVC8CGn4jPeDXlkKKXjUX/Untitled?node-id=96%3A9
рендерится всё равно, но без данных. Я пока не придумал как это переделать, и потому не могу точно утверждать, что избавлюсь от проверки на  null,  в  данном случае с помощью null  я обозначаю отсутствие второго массива в items.

2021-12-10 14:43 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <Layout flexBasis={520} />
@TFK70 Тут, они не дублируются, задумка: иметь два лэйаута, один из которых не будет сжиматьсяни при каких обстоятельствах, обеспечивая нужный нам отступ. Второй будет сжиматься в зависимости от контента. Напиши, если так делать не нужно.

2021-12-10 14:44 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <Layout flexBasis={520} />
@gochicus я не понимаю зачем
Покажи это место в дизайне

2021-12-13 16:38 UTC, TFK70 commented on site/course-description-fragment/src/course-description.component.tsx
> +                  {' '}
@gochicus не вижу здесь тега outdated
Это все еще в коде находится?

2021-12-13 16:39 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <Layout flexBasis={520} />
@gochicus ?

2021-12-13 16:39 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +      <ImageBlock />
@gochicus ?

2021-12-13 17:59 UTC, gochicus commented on site/course-description-fragment/src/course-description.component.tsx
> +                  {' '}
@TFK70  Да, хотя я чистил от этих символов, не уверен как так получилось, ещё раз почищу.

2021-12-13 18:04 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <Layout flexBasis={520} />
@TFK70  https://www.figma.com/file/ayVC8CGn4jPeDXlkKKXjUX/Untitled?node-id=96%3A9  идея в том, что текст разной длинны может находится как на максимальном расстоянии от блока, равному сумме базисов двух лэйаутов, так  и на минимальном - второй не сжимаемый лэйаут.  Как уже писал, это просто идея, напиши если так неправильно делать.

2021-12-13 18:05 UTC, TFK70 commented on site/course-description-fragment/src/course-description.component.tsx
> +                  {' '}
@gochicus сделай рекурсивный поиск через шторм, замени все {' '} (погугли хоткей)
Любое вхождение этой конструкции - лишнее, так что вычищай все

2021-12-13 18:07 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <Layout flexBasis={520} />
@gochicus пофикси ссылку на дизайн, у тебя нет ссылки на конкрейтный объект (ну или скрин кинь)
![image](https://user-images.githubusercontent.com/62806448/145865132-a1fec311-8f25-4db7-a6d6-aeff710af3c6.png)

2021-12-13 18:13 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <Layout flexBasis={520} />
@TFK70 
![maket](https://user-images.githubusercontent.com/49765285/145865936-0dcc85a2-c035-40d0-a41c-f33f1d5ba7f8.png)

2021-12-13 18:18 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <Layout flexBasis={520} />
@gochicus теперь мне твоя идея стала еще более неясной

Ты, видимо, неправильно позиционируешь текст. У тебя же в дизайне все есть: контейнер в котором находятся скиллы в колонку и его отступ от картинки справа

![image](https://user-images.githubusercontent.com/62806448/145866543-87825c46-06c7-49ea-a169-ddbf0f6dd2cf.png)

Разметь на этой картинке какой из лейаутов у тебя за что отвечает

2021-12-13 18:34 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <Layout flexBasis={520} />
@TFK70  тут вот этот отступ имеется в виду, но решение действительно неправильное, вызвано тем, что у меня мапятся блоки текста одинакового размера, хотя по макету они разные. В общем, переделаю здесь верстку. 
![image](https://user-images.githubusercontent.com/49765285/145868026-291187ae-007b-46ed-9fc5-1ef7b55358d0.png)

2021-12-13 18:36 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <Layout flexBasis={520} />
@gochicus вообще ничего не понял
Скажи что ты сейчас собираешься делать

2021-12-13 18:40 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <Layout flexBasis={520} />
@TFK70  Поменять разметку,  поместить блок с текстом и лэйаут с отступом в один роу. Когда  блоки текста будут различаться в размере, будет различаться и отступ.

2021-12-13 18:42 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <Layout flexBasis={520} />
@gochicus у контейнеров для итемов должен быть конкретный размер, смысл тогда контейнеризации? Ты мне свое решение так и не объяснил, я не понимаю что тебе неясно и что у тебя не получается

2021-12-13 18:49 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <Layout flexBasis={520} />
@TFK70  да вроде ничего неясного нет, просто реализация плохая. Перепишу фрагмент.

2021-12-13 18:54 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <Layout flexBasis={520} />
@gochicus нарисуй в фигме (или в любом другом месте) что ты собираешься делать с комментариями, я все еще ничего не понимаю, мне "перепишу фрагмент" вообще ни о чем не говорит, мне нужны гарантии что ты действительно понял что именно тут не так и ты понимаешь что будешь делать

2021-12-13 19:03 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <Layout flexBasis={520} />
@TFK70 
![plan](https://user-images.githubusercontent.com/49765285/145872278-b0abbfc1-9ab3-4303-a100-ef14e00413c5.png)

2021-12-13 19:12 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <Layout flexBasis={520} />
@gochicus выглядит валидно

2021-12-14 21:37 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/item/item.interface.ts
> +  main: any
@gochicus ?

2021-12-14 21:44 UTC, TFK70 requested changes

2021-12-14 21:44 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +            <Layout style={{ whiteSpace: 'nowrap' }}>
Что за инлайн стили? И почему это тоже повторяется вручную кучу раз? 160+ строк на файл с версткой - это же катастрофа, как с этим работать вообще?

2021-12-15 07:47 UTC, gochicus commented on site/header-fragment/src/header.component.tsx
> +            <Layout style={{ whiteSpace: 'nowrap' }}>
@TFK70 эти инлайн стили нужны для изменения дефолтного поведения текста внутри Layout, теперь при уменьшении ширины контейнера текст не переносится на отдельную строку, что позволяет нормально работать с overflow и zIndex. **Для чего оно было мне нужно?**  Overflow позволяет вывести текст в поле красной полоски из макета без применения абсолютного позиционирования, выглядит это вот так:
![image](https://user-images.githubusercontent.com/49765285/146143406-24728484-84b1-4a36-ab30-9ea1a1b48cc9.png)
**Почему инлайн стили?** Этот стиль меняет дефолтное поведение текста внутри лэйаута, а такое изменение по всему проекту мне не нужно. Если сам подход к работе с красной полоской тебя устроит, то можно будет сделать отдельный ui компонент с подобным поведением.  **Помню ли я, что  работать с красной полоской мне не нужно?** Да, но я решил отправить на проверку идею для работы с ней, именно поэтому она присутствует только в мобильной версии хэдера( в десктопе всё на флексах). Если подход тебя утсроит, я сделаю аналогично по всему проекту ( в тех местах, где полоса должна присутствовать) Если нет, то убрать инлайн стили и саму полосу займет не больше пяти минут.

2021-12-15 07:50 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +            <Layout style={{ whiteSpace: 'nowrap' }}>
Тут скорее вопрос к тому, почему стили влияющие на текст находятся в лейауте, а не в <Text>, тем более там есть соответствующие пропы и инлайнить стили не нужно будет

2021-12-15 08:06 UTC, gochicus commented on site/header-fragment/src/header.component.tsx
> +            <Layout style={{ whiteSpace: 'nowrap' }}>
@TFK70 В таком случае, я неправильно понял твой реквест, формулировка про инлайн стили была не чёткой. По поводу  размеров кода: наверное, можно вынести код с иконками, будет компонент social. Но больше всего строк занимают блоки с текстом, их можно мапать, по три блока. Но это, с другой стороны, по компоненту на каждые три блока текста. Если всё мапать вместе лого в мобильной версии, то тут надо городить сложную структуру ради пары десятков строк. Выносить колонки с текстом смысла не вижу.  В общем, оптимизирую немного. Напиши, если я неправильно всё это себе представляю.  По поводу красной полосы, подход в целом нормальный? Можно так  с ней работать?

2021-12-15 08:14 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +            <Layout style={{ whiteSpace: 'nowrap' }}>
Про эту полоску я вроде ничего и не говорил, у меня были вопросы к полоскам у изображений - я просил их убирать

Тебе твою верстку нужно разбить на сущности, нужно чтобы код был читабельный и повторяющаяся конструкция глаза не резала

2021-12-15 08:20 UTC, gochicus commented on site/header-fragment/src/header.component.tsx
> +            <Layout style={{ whiteSpace: 'nowrap' }}>
@TFK70  

> Про эту полоску я вроде ничего и не говорил, у меня были вопросы к полоскам у изображений - я просил их убирать

В таком случае возникло  грандиозное недопонимание, но вроде как от неё: 
https://www.figma.com/file/ayVC8CGn4jPeDXlkKKXjUX/Untitled?node-id=183%3A9
также нужно было избавиться просто потому, что она была абсолютно позиционирована у меня практически по всему проекту.

2021-12-15 16:39 UTC, TFK70 requested changes

2021-12-15 16:39 UTC, TFK70 commented on site/header-fragment/src/messages.ts
> +    defaultMessage: phoneNumber,
А зачем ты это в интл засунул?

2021-12-15 16:39 UTC, TFK70 commented on site/portfolio-fragment/src/portfolio.component.tsx
> +  const genres = [
Это тоже идет с бека

2021-12-15 16:39 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +      <Box width='100px' backgroundColor='transparent' />
Это за что отвечает?

2021-12-15 16:39 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +      <Box width='105px' backgroundColor='dullRed' />
И это

2021-12-15 16:39 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/item/item.interface.ts
> +  mainText: any[]
почему any? почему массив? я вообще изначально хотел узнать что тут лежит

2021-12-15 16:39 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/item/list.component.tsx
> +  mainText !== !mainText
`true !== false`?
За что это условие отвечает?

2021-12-15 16:39 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/item/list.component.tsx
> +    ? mainText.map((item) => (
И почему снова тернарники, а не Condition?

2021-12-15 16:39 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/item/list.component.tsx
> +          </Layout>{' '}
Я же просил рекурсивным поиском по проекту пройтись

2021-12-15 16:39 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.component.tsx
> +          <Item header={item[0]} mainText={item[1]} />
Что такое item[0] и item[1]?

2021-12-15 16:39 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.interface.ts
> +  items: any[]
any

2021-12-16 07:34 UTC, gochicus commented on site/header-fragment/src/messages.ts
> +    defaultMessage: phoneNumber,
@TFK70  для удобства,  вот здесь мапится наш текст: 
https://github.com/torin-asakura/drum-in/blob/feature/apply-styles/site/header-fragment/src/header.component.tsx#L85
Айтемы приходят сразу в formatMessage, поэтому, чтобы не плодить дополнительных условий, все данные хранятся в фале messages. Но телефонный номер должен приходить с бэка, соответствующая переменная  есть в mocks. В общем, чтобы совместить эти два условия, переменная из mocks  просто импортируется в message, что позволяет мапать этот блок текста как и все остальные. Если это, по каким-то причинам, неприемлемо, напиши.

2021-12-16 07:50 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +      <Box width='105px' backgroundColor='dullRed' />
@TFK70  91 строка это красная линия на макете. 
![image](https://user-images.githubusercontent.com/49765285/146328239-ae6bc6df-14d4-47ae-99fa-2c07f381beec.png)
Насчет строки 90, это просто полоска белого цвета определенной ширины, она нужна, чтобы контейнер с текстом не расширялся. Наложение текста поверх других блоков осуществляется за счёт overflow,  и наиболее соответствующий макету overflow получается при использовании контейнера определённого размера, где и хранится наш текст. Иными словами это просто подпорка.  BackgroundColor ей не нужен совсем, деллал для удобства поиска. Без неё самой, в принципе, тоже можно обойтись, но с ней удобнее.

2021-12-16 07:55 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills/item/item.interface.ts
> +  mainText: any[]
@TFK70 
https://github.com/torin-asakura/drum-in/blob/feature/apply-styles/site/data/src/mocks.ts#L2
В айтем приходит массив, который содержит заголовок типа string и массив со строками, представляющими основной текст.
![image](https://user-images.githubusercontent.com/49765285/146330596-fa7c3dba-9b0b-43e1-8ffb-f611344857b4.png)

2021-12-16 07:59 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills/item/list.component.tsx
> +  mainText !== !mainText
@TFK70 так воспринял твой комментарий: https://github.com/torin-asakura/drum-in/pull/27#discussion_r766645644
Проверяется есть ли текст, но проверка, пожалуй, действительно не самая удачная, поправлю.

2021-12-16 08:02 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills/item/list.component.tsx
> +    ? mainText.map((item) => (
@TFK70  а можешь пояснить почему будет предпочтительнее пользоваться Condition в данной ситуации? Тут просто  должно быть отсутствие рендера, если условие не выполняется, а не альтернативный рендер.

2021-12-16 08:06 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills/skills.component.tsx
> +          <Item header={item[0]} mainText={item[1]} />
@TFK70   В Skills приходит массив, его элементы пробрасываются в виде заголовка и основного текста в айтем, подробнее ответил здесь: https://github.com/torin-asakura/drum-in/pull/27#discussion_r770296287

2021-12-16 08:16 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills/item/list.component.tsx
> +          </Layout>{' '}
@TFK70 не знаю как так выходит, откатился до вчерашнего коммита, и там этого нет.
![image](https://user-images.githubusercontent.com/49765285/146333517-477a0c40-70fe-41a3-a3e1-4faddab27260.png)

2021-12-16 09:55 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills/item/list.component.tsx
> +  mainText !== !mainText
@TFK70 я  подумал, что речь идет о непустом значении и что оно  true. То есть, если наш main  что-то возвращает, то это  true, проверка должна была выявить не  является ли значение противоположным. Выглядело логично.

2021-12-16 09:56 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/item/list.component.tsx
> +    ? mainText.map((item) => (
@gochicus за тем же зачем ты называешь файлы с компонентами `item.component.tsx`, а не `Item.tsx`, за тем же зачем ты делаешь фрагменты и отделяешь слой application. Это называется кодстайл, и что тебя так смущает здесь в Condition? Не понимаю

2021-12-16 12:25 UTC, TFK70 requested changes

2021-12-16 12:25 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +                      {intl.formatMessage(item)}
это пробел чтоли?

2021-12-16 12:25 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +                      {phoneNumber}
и это, тут тоже пробел?

2021-12-16 12:25 UTC, TFK70 commented on site/portfolio-fragment/src/portfolio.component.tsx
> +                  <>
Почему ты не выносишь это в отдельную сущность? Так же удобнее и чище

2021-12-16 12:25 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.interface.ts
> +  items: (string | string[])[][]
воувоувоу, если честно я впервые такую конструкцию вижу
дай пример того, что там лежит

2021-12-16 12:25 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.component.tsx
> +          <Item header={item[0]} content={item[1]} />
Все-равно не могу понять как это работает
Покажи в дизайне что такое Item и что такое item[0] и item[1]

2021-12-16 12:27 UTC, TFK70 requested changes

2021-12-16 12:27 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/item/list.component.tsx
> +  <Condition match={Array.isArray(mainText)}>
Так, окей, а где тогда обработка случая когда mainText - string? У тебя же в типах указано что это может быть стрингом

2021-12-16 12:58 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills/skills.component.tsx
> +          <Item header={item[0]} content={item[1]} />
@TFK70 вот данные айтема  https://github.com/torin-asakura/drum-in/blob/feature/apply-styles/site/data/src/mocks.ts#L1-L12
<img width="1152" alt="items" src="https://user-images.githubusercontent.com/49765285/146376089-9cb68a2b-99b3-4215-b142-e51215265395.png">

2021-12-16 12:59 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.interface.ts
> +  items: (string | string[])[][]
@gochicus теперь понимаешь почему тебе не говорили делать моки? Почему ты решил что данные будут приходить именно в таком виде?

2021-12-16 13:01 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.interface.ts
> +  items: (string | string[])[][]
@gochicus теперь забудь что ты их делал. Перепиши интерфейсы для компонентов где есть похожая ситуация. Я тебе вроде так и сказал до этого: сначала опиши интерфейсы для компонентов, но из-за того что моки ты зачем-то сделал и сделал до описания интерфейсов компонентов, у тебя в коде происходит подобная каша...

2021-12-16 13:02 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.component.tsx
> +          <Item header={item[0]} content={item[1]} />
Ну тут аналогично абсолютно........

2021-12-16 13:14 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills/skills.interface.ts
> +  items: (string | string[])[][]
@TFK70 

>  Перепиши интерфейсы для компонентов где есть похожая ситуация. 

Не совсем понял какие именно ты имеешь в виду.

2021-12-17 12:06 UTC, TFK70 commented on site/header-fragment/src/messages.ts
> +    defaultMessage: phoneNumber,
@gochicus насчет удобства понял
С точки зрения логики - да, это неприемлемо, так как интл тоже не для красоты используется. Ну и этим данным в интле, собственно, не место, но в нашем случае можно все пока оставить так (но это частный случай), все-равно как будут реальные данные флоу работы с ними немного поменяется

2021-12-17 12:23 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +      <Box width='105px' backgroundColor='dullRed' />
@gochicus почему это нельзя было вынести в отдельную сущность? Опять

https://codesandbox.io/s/reverent-thunder-wufep?file=/src/fragment/container/container.styles.ts

Зачем это в таком виде оставлять в верстке? Очевидно что к таким вещам будет куча вопросов, они неочевидные и сложны для понимания, для этого ты должен их разделять

2021-12-17 13:14 UTC, TFK70 requested changes

2021-12-17 13:14 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.interface.ts
> +      content: string[]
создай здесь интерфейс Item, не мешай все в одну кучу

2021-12-17 13:14 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.interface.ts
> +      content: string[]
и ни к чему помещать это в textBlock если это единственное свойство

2021-12-17 13:14 UTC, TFK70 commented on site/skills-to-learn-fragment/src/data.ts
> +  textBlock: [
зачем ты моки снова трогаешь? я же тебе сказал удали их

2021-12-17 13:14 UTC, TFK70 commented on site/about-fragment/package.json
>      "@emotion/react": "^11.6.0",
почему это не в пирах? я же просил порядок на пректе навести

2021-12-17 13:14 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +          style={{ zIndex: 1 }}
так делать нельзя

2021-12-17 13:14 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +          style={{ zIndex: 1 }}
неявные вещи - под сущности

2021-12-17 13:14 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +        <Box backgroundColor='dullRed' width='105px' flexShrink={0} />
а это что?

2021-12-17 13:14 UTC, TFK70 commented on site/skills-presentation-fragment/src/skills-presentation.component.tsx
> +        <Item item={['РАЗВИТИЕ ЧУВСТВА ВРЕМЕНИ']} />
И когда будут настоящие данные ты начнешь копаться в своей верстке?

2021-12-17 13:14 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +        <BackgroundField />
Нет, в моем примере не так было. Это не логично. Ты должен сделать так же, как в примере, без придумок
Единственное, что тебе нужно изменить - выполнить пример в соответствии с кодстайлом: использовать @emotion/styled и тп, но сущеости должны быть те же

2021-12-17 13:14 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills/skills.component.tsx
> +      {items.textBlock.map((item) => (
items.textBlock? item это массив, как у массива может быть свойство textBlock? тоже к вопросу почему ты моки не убрал

2021-12-17 13:31 UTC, gochicus commented on site/skills-to-learn-fragment/src/data.ts
> +  textBlock: [
@TFK70 я не совсем понимаю куда мне деть эти данные, в сам компонент что ли? Их многовато получается.   Это как бы не моки, от   @site/data  я избавился, да, а это в отдельный файл поместил просто потому, что иначе получается громоздко слишком. Но если нужно, помещу их в сам компонент.

2021-12-17 13:33 UTC, TFK70 commented on site/skills-to-learn-fragment/src/data.ts
> +  textBlock: [
тебе зачем все эти данные? возьми только часть из них, покажи что у тебя компонент работает нормально и все

2021-12-17 13:33 UTC, TFK70 commented on site/skills-to-learn-fragment/src/data.ts
> +  textBlock: [
и да, пусть они будут в компонентах

2021-12-17 13:36 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +        <Box backgroundColor='dullRed' width='105px' flexShrink={0} />
И почему ты ее в соответствии с примером не оформил? Тут же ситуация 1 в 1

2021-12-21 14:42 UTC, TFK70 requested changes

2021-12-21 14:42 UTC, TFK70 commented on site/header-fragment/src/container/container.component.tsx
> +    <Layout style={{ zIndex: 1 }}>{children}</Layout>
зачем здесь zIndex?

2021-12-21 14:42 UTC, TFK70 commented on site/header-fragment/src/container/container.interface.ts
> +  chidren?: any
убери, это входит в FC

2021-12-21 14:42 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-list/skills-list.component.tsx
> +                <Layout width='375px' style={{ position: 'relative' }}>
Что это?

2021-12-21 14:42 UTC, TFK70 commented on site/course-description-fragment/src/course-description-content/course-content.interface.ts
> +  mobile: boolean
Снова? Мы так нигде не делаем, только средствами styled-system

2021-12-21 14:42 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-list/skills-list.component.tsx
> +          <Layout width='320px' style={{ position: 'relative' }}>
И толку от того что ты разделил что-то на какие-то сущности если у тебя все-равно грязь в верстке? Что это вообще и зачем?

2021-12-21 14:56 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills-list/skills-list.component.tsx
> +          <Layout width='320px' style={{ position: 'relative' }}>
@TFK70  это не грязь,  между отображением  мобильной версии страницы  в инспекторе разработчика и в мобильнике с браузера есть разница. Вот так выглядит  страница без этого контейнера у меня на мобилке:
![image](https://user-images.githubusercontent.com/49765285/146950042-9d2ea7e2-e548-40c0-b705-f0fb03194209.png)
Вот это же место с мобильника, но я уже вернул размер и стиль на место:
![image](https://user-images.githubusercontent.com/49765285/146950489-25a17918-dd92-4ef5-ac4e-2f8013b901c9.png)
Суть решения  - удерживать компонент в контейнере с относительным позиционированием и жёстко заданным размером.

2021-12-21 14:59 UTC, gochicus commented on site/course-description-fragment/src/course-description-content/course-content.interface.ts
> +  mobile: boolean
@TFK70 поясни, не понял к чему это относится. Если только к интерфейсу, то без него код не проходит тайпчеки.

2021-12-21 15:02 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-list/skills-list.component.tsx
> +          <Layout width='320px' style={{ position: 'relative' }}>
@gochicus ты же в курсе что "сделать чтобы просто работало" - не совсем наш подход? Через 2 месяца ни ты, ни я, ни кто-то другой не поймет что это вообще такое, придется выкинуть и переписать все с нуля. Это грязь потому что ты снова не вынес ее в отдельную сущность и оставил это в верстке. Суть тех или иных компонентов системы не должна поясняться через комментарии на гитхабе, ты не для меня это делаешь

2021-12-21 15:05 UTC, TFK70 commented on site/course-description-fragment/src/course-description-content/course-content.interface.ts
> +  mobile: boolean
@gochicus почему ты снова отделяешь мобильную от десктопной версии как-то по-своему через какие-то пропы? Ты хоть где-то такое видел?

2021-12-21 15:06 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills-list/skills-list.component.tsx
> +                <Layout width='375px' style={{ position: 'relative' }}>
@TFK70 
![image](https://user-images.githubusercontent.com/49765285/146951453-a59a07df-3c0a-4528-9c99-1133618b4b72.png)
В первом контейнере , соответствующему размеру изображения,  центрируется второй контейнер, который содержит в себе компонент, в котором есть абсолютное позиционирование .

2021-12-21 15:07 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-list/skills-list.component.tsx
> +                <Layout width='375px' style={{ position: 'relative' }}>
@gochicus отсылаюсь [сюда](https://github.com/torin-asakura/drum-in/pull/27#discussion_r773209214), все эти вещи должны доноситься через код, а не через гитхаб который имеет к коду только косвенное отношение

2021-12-21 15:18 UTC, gochicus commented on site/course-description-fragment/src/course-description-content/course-content.interface.ts
> +  mobile: boolean
@TFK70 м,  тут не совсем так, здесь компонент вообще один и он отрендерит мобильную или десктопную версию в зависимости от условия. Мобайл это условие, которые мы пробрасываем для компонента. 
https://github.com/torin-asakura/drum-in/blob/feature/apply-styles/site/course-description-fragment/src/course-description-content/cousre-content.component.tsx#L74 
Какое условие будет проброщено компоненту как раз решается через styled-system:
https://github.com/torin-asakura/drum-in/blob/feature/apply-styles/site/course-description-fragment/src/course-description.component.tsx#L33

2021-12-21 15:19 UTC, gochicus commented on site/skills-to-learn-fragment/src/skills-list/skills-list.component.tsx
> +          <Layout width='320px' style={{ position: 'relative' }}>
@TFK70  Я правильно понимаю, что мне нужно сделать отдельную сущность в которую помещать компонент Container  во всех местах, где это требуется?

2021-12-21 15:19 UTC, TFK70 commented on site/course-description-fragment/src/course-description-content/course-content.interface.ts
> +  mobile: boolean
@gochicus я видел где и как оно используется
Повторюсь: ты где-то такое видел?

2021-12-21 15:24 UTC, gochicus commented on site/course-description-fragment/src/course-description-content/course-content.interface.ts
> +  mobile: boolean
@TFK70 Компонент, который отдает разный контент в зависимости условий, заданных в Condition?  Да, и сам такое использовал.  Но ты ведь не об этом? Уточни суть проблемы.

2021-12-21 15:47 UTC, gochicus commented on site/header-fragment/src/container/container.component.tsx
> +    <Layout style={{ zIndex: 1 }}>{children}</Layout>
@TFK70  потестил, действительно здесь не нужен. Остался от прошлых реализаций.

2021-12-21 16:31 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn.component.tsx
> +      <Box width='105px' backgroundColor='dullRed' />
тогда resolved

2021-12-21 18:51 UTC, TFK70 requested changes

2021-12-21 18:51 UTC, TFK70 commented on site/portfolio-fragment/src/mobile-sized-container/container-mobile-sized.component.tsx
> +export const ContainerMobileSized: FC<string> = ({ children, width }) => (
Повесить relative на родителя

2021-12-21 18:51 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +          <DesktopText />
юзать styled-system

2021-12-21 18:51 UTC, TFK70 commented on site/individual-lessons-fragment/src/individual-lessons.component.tsx
> +          zIndex={1}
Убрать под сущность

2021-12-21 18:51 UTC, TFK70 commented on site/header-fragment/src/container/container.component.tsx
> +  <Row justifyContent='flex-end'>
В чем цель этого контейнера?

2021-12-21 18:53 UTC, gochicus commented on site/header-fragment/src/container/container.component.tsx
> +  <Row justifyContent='flex-end'>
@TFK70  по аналогии с вот этим: 
https://codesandbox.io/s/reverent-thunder-wufep?file=/src/fragment/container/container.styles.ts
Твой пример взял за основу, оставил в нём только самое необходимое, максимально упростив.

2021-12-21 18:55 UTC, gochicus commented on site/header-fragment/src/header.component.tsx
> +          <DesktopText />
@TFK70  не понял реквест

2021-12-21 19:05 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +          <DesktopText />
@gochicus ты разделил десктоп/мобилку на разные компоненты?

2021-12-21 20:18 UTC, TFK70 commented on site/header-fragment/src/container/container.component.tsx
> +  <Row justifyContent='flex-end'>
@gochicus я не совсем понимаю как он работает тогда
Если Line позиционируется через position absolute, то где контейнер с position relative? Или я что-то упустил?

2021-12-22 07:05 UTC, gochicus commented on site/header-fragment/src/header.component.tsx
> +          <DesktopText />
@TFK70 да, https://github.com/torin-asakura/drum-in/blob/feature/apply-styles/site/header-fragment/src/header.component.tsx#L54

2021-12-22 08:36 UTC, gochicus commented on site/individual-lessons-fragment/src/individual-lessons.component.tsx
> +          zIndex={1}
@TFK70 это фон для всего десктопного компонента, тут что нужно вынести: текст или всю вёрстку мобильную с десктопной сделать компонентами?

2021-12-22 08:58 UTC, gochicus commented on site/header-fragment/src/container/container.component.tsx
> +  <Row justifyContent='flex-end'>
@TFK70 Контейнер с position relative изначально был,  но, мне было сложно управлять поведением всего компонента. Теперь он управляется снаружи.  https://github.com/torin-asakura/drum-in/blob/feature/apply-styles/site/skills-to-learn-fragment/src/skills-list/skills-list.component.tsx#L123 
Line занимает позицию в контейнере со стилем position:relative. Компонент с потомками ведёт себя как обычный флекс компонент.

2021-12-22 12:22 UTC, gochicus commented on site/individual-lessons-fragment/src/individual-lessons.component.tsx
> +          zIndex={1}
@TFK70  ?

2021-12-22 12:23 UTC, gochicus commented on site/header-fragment/src/container/container.component.tsx
> +  <Row justifyContent='flex-end'>
@TFK70 Это нужно как-то менять?

2021-12-22 12:57 UTC, TFK70 requested changes

2021-12-22 12:57 UTC, TFK70 commented on site/individual-lessons-fragment/src/individual-lessons.component.tsx
> +          zIndex={1}
@gochicus вынеси этот Box в Container

2021-12-22 12:57 UTC, TFK70 commented on site/individual-lessons-fragment/src/individual-lessons.component.tsx
> +    <Layout width='100%'>
Зачем этот лейаут?

2021-12-22 13:06 UTC, gochicus commented on site/individual-lessons-fragment/src/individual-lessons.component.tsx
> +    <Layout width='100%'>
@TFK70  ограничивает Column по высоте, не дает наезжать на нижний фрагмент.   Насчёт Box не понял идею.

2021-12-22 13:10 UTC, TFK70 commented on site/individual-lessons-fragment/src/individual-lessons.component.tsx
> +    <Layout width='100%'>
@gochicus какой Column? Он оборачивает весь фрагмент и ничего не ограничивает, можешь продемострировать как это происходит?

Насчет идеи с Box:

Это:

```javascript
        <Box
          width={['320px', '320px', '100%']}
          height={['290px', '290px', '581px']}
          backgroundColor='dullBlack'
          justifyContent='center'
          zIndex={1}
        >
```

Должно превратиться вот в это:

```javascript
<Container>
```

2021-12-22 13:15 UTC, gochicus commented on site/individual-lessons-fragment/src/individual-lessons.component.tsx
> +    <Layout width='100%'>
@TFK70  

> можешь продемострировать как это происходит? 

вот так без Layout

![image](https://user-images.githubusercontent.com/49765285/147098175-e6c8f36d-2e2b-4e2c-9c8a-3bed998824e2.png)

2021-12-22 17:08 UTC, gochicus commented
@TFK70  в мобильной версии присутствуют  элементы переключения слайдера( или показывающие текущий активный слайд, не уверен), должны ли они присутствовать в финальной верстке, с учетом того, что изображения добавлять не нужно? 
![image](https://user-images.githubusercontent.com/49765285/147129246-3a40b1bf-5f0d-466f-82e2-3970ff42c7a0.png)
![image](https://user-images.githubusercontent.com/49765285/147129392-93a380c1-1f3d-49db-9e14-d436e51d1b80.png)

2021-12-22 19:22 UTC, TFK70 commented
> @TFK70 в мобильной версии присутствуют элементы переключения слайдера( или показывающие текущий активный слайд, не уверен), должны ли они присутствовать в финальной верстке, с учетом того, что изображения добавлять не нужно?
> ![image](https://user-images.githubusercontent.com/49765285/147129246-3a40b1bf-5f0d-466f-82e2-3970ff42c7a0.png)
> ![image](https://user-images.githubusercontent.com/49765285/147129392-93a380c1-1f3d-49db-9e14-d436e51d1b80.png)

Нет, слайдер делать не нужно

2021-12-23 12:44 UTC, gochicus commented
@TFK70 готов к ревью, где-нужно было - стили поправил, по коду тоже устранил недочёты.

2021-12-23 12:46 UTC, TFK70 commented
> @TFK70 готов к ревью, где-нужно было - стили поправил, по коду тоже устранил недочёты.

У кнопок и ссылок нету ховеров - синкни весть этот интерактив с продом

2021-12-23 15:35 UTC, gochicus commented
@TFK70 возник вопрос, смотрю как оно в мисике сделан, в этих местах:
https://github.com/torin-asakura/misik/blob/master/ui/button/src/styles/appearance/appearance.styles.ts#L9
https://github.com/torin-asakura/misik/blob/master/ui/button/src/styles/appearance/abstract/primary-colors.styles.ts#L4
theme приходит непосредственно из провайдера? Или я неправильно понимаю этот момент?

2021-12-23 15:38 UTC, TFK70 commented
@gochicus не надо делать как в Мисике, уже говорил ведь
Сделай лучше как тут: https://github.com/YouThinkResearch/web/blob/master/frontend/ui/select/src/button/button.styles.ts

2021-12-23 16:05 UTC, gochicus commented
@TFK70 https://github.com/YouThinkResearch/web/blob/master/frontend/ui/select/src/button/button.styles.ts тот же вопрос касаемо этой реализации, здесь theme  из провайдера приходит?  У меня подозрение, что theme не проходит, не знаю как проверить.  Работала только реализация, которая уже закомичена, где есть  prop и обращение к теме проичходит в виде строки внутри  prop. Любые реализации с обращением непосредственно к theme не работают.

2021-12-23 16:07 UTC, TFK70 commented
@gochicus да, из провайдера

2021-12-24 11:10 UTC, gochicus commented
@TFK70 интерактив добавлен, можно смотреть

2021-12-24 11:17 UTC, TFK70 requested changes
Мне кажется здесь есть явные несостыковки
И у всех элементов должен быть transition, кол-во секунд тоже возьми с прода

![image](https://user-images.githubusercontent.com/62806448/147348332-dba69ce8-eeb4-4135-a962-70af1c8408aa.png)
![image](https://user-images.githubusercontent.com/62806448/147348311-8f1a4d2c-68e5-478b-a709-487ff3f0483f.png)

2021-12-24 11:26 UTC, gochicus commented
@TFK70  у меня оно выглядит вот так, что-то не могу понять как так получается, может снова шрифтына дефолтные ушли, проверю. 
![image](https://user-images.githubusercontent.com/49765285/147348917-865e9bc6-b462-46ef-9883-681bd815d29d.png)

2021-12-24 11:37 UTC, gochicus commented
@TFK70 не могу понять почему у тебя так, шрифты вроде доходят и всё нормально выглядит. 

https://user-images.githubusercontent.com/49765285/147349540-2467af76-96c2-4fcd-85e1-89bde1561b08.mp4

2021-12-24 11:41 UTC, TFK70 commented
@gochicus а почему это кнопка? Это же ссылка

2021-12-24 11:42 UTC, TFK70 requested changes

2021-12-24 11:42 UTC, TFK70 commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
Почему это кнопка? Это же ссылка

2021-12-24 12:00 UTC, gochicus commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@TFK70  куда нужно вешать события, которые будут контролировать состояние появления линии под текстом?

2021-12-24 12:09 UTC, TFK70 commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@gochicus не совсем корректный вопрос. Вешать их очевидно нужно на саму ссылку, ты сейчас так и делаешь, у тебя проблема в том, где это контролировать. Контролировать это нужно непосредственно внутри самой ссылки, сейчас ты делаешь это снаружи, что влечет за собой лишнюю логику. Создай `@ui/link` и опиши всю логику со стилями там

2021-12-24 12:19 UTC, gochicus commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@TFK70 уточню,  я могу использовать Button внутри компонента Link?

2021-12-24 12:20 UTC, TFK70 commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@gochicus зачем?

2021-12-24 12:23 UTC, gochicus commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@TFK70  думал прошлую реализацию засунуть внутрь компонента, но попробую по другому.

2021-12-24 12:27 UTC, TFK70 commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@gochicus а зачем?

2021-12-24 12:29 UTC, gochicus commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@TFK70   с ней очевидно куда именно события можно навесить.

2021-12-24 12:32 UTC, TFK70 commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@gochicus 
```javascript
export const Link = styled.link(baseStyles, appearanceStyles, shapeStyles)
```

2021-12-24 12:38 UTC, gochicus commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@TFK70  а как якоря делать нужно?

2021-12-24 12:42 UTC, TFK70 commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@gochicus http://htmlbook.ru/samhtml/yakorya

2021-12-24 14:28 UTC, gochicus commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@TFK70 можешь пояснить как это должно работать? 
https://github.com/torin-asakura/drum-in/pull/27/commits/c0d349a24447951fa5c15ea3ac295e96028cfa97#diff-989940038ae2c23a8cfa00912bc7925d964039cb26d07cbcaf69756d351752ceR15
Компонент ничего не оборачивает, потомков у него нет, с якорем тоже непонятно.

2021-12-24 14:34 UTC, TFK70 commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@gochicus 

> потомков у него нет

в смысле потомков нет? А где они должны быть по-твоему?

> Компонент ничего не оборачивает

А что он должен оборачивать?

> с якорем тоже непонятно

Ты прочитал про то как он работает? Это очень простая вещь которая делается с помощью обычной ссылки

2021-12-24 14:39 UTC, gochicus commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@TFK70 
`   <Link href='#lessons' id='test'/>`
`    <Link name ='lessons'>`
 Вот так оно должно работать? 

> в смысле потомков нет? А где они должны быть по-твоему?
В коде я вижу самозакрывающийся элемент.  Стандартная ссылка в html текст обычно оборачивает. Этот момент несколько не ясен.

2021-12-24 14:40 UTC, TFK70 commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@gochicus 

```javascript
<a href='#lessons'>Click</a>
<div id='lessons' />
```

2021-12-24 15:40 UTC, gochicus commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@TFK70 а как у него стили работают?   Подключил стили appearance, чтобы проверить
`const StyledLink = styled.a(baseStyles,appearanceStyles)`
Ховер, я так понял,  работает внутри компонента, мне непонятно могут ли appearanceStyles применяться так, как в коде, который привел или нужно вызывать их с ховером( что логично), но ховер в такой ситуации не определён.

2021-12-24 15:52 UTC, TFK70 commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@gochicus в смысле как стили работают? Ты впервые в жизни styled компонент видишь? Вообще ничего не понимаю, это просто обычный компонент, какие тут вообще проблемы могут возникать? Ты же уже десятки таких писал, в чем дело?

2021-12-24 15:59 UTC, gochicus commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@TFK70  я пытался применить те стили, что ты оставил при инициации компонента, сделал вот так: 

> const StyledLink = styled.a(baseStyles,appearanceStyles)

Стили не применяются. Пытался разобраться в чем дело, потом обратился к тебе с вопросом. Возможно, я как-то не так их применяю.

2021-12-24 16:04 UTC, TFK70 commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@gochicus все правильно, а как именно они не работают?

2021-12-24 16:10 UTC, gochicus commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
@TFK70 в стилях при инициализации был такой код: 
`export const appearanceStyles: styleFn = ({ hover }) => ({
  color: hover ? 'red' : 'black',
})`
Я поменял только цвет с синего на красный.  Линк у меня выглядит вот так:
`<Link href ='#course' >
          <Layout>
            <Text
                color='black'
                fontSize='big'
                fontWeight='normal'
                textDecoration ={line==='rythm'?'underline':'none'}
                lineHeight='regular'
                letterSpacing='0.15em'
              >
                {intl.formatMessage(messages.rythm)}
             </Text>
        </Layout>
        </Link>`
Я пробовал убирать Layout, который оборачивает текст, но при движении мыши по тексту смены цвета не произошло.

2021-12-24 16:21 UTC, TFK70 commented on site/header-fragment/src/navigation/navigation.component.tsx
> +          <Button
Без Text все норм будет

2021-12-24 17:30 UTC, TFK70 requested changes

2021-12-24 17:30 UTC, TFK70 commented on site/course-description-fragment/src/course-description.component.tsx
> +                      letterSpacing='0.15em'
Я думаю будет уместно вынести эти стили в компонент

2021-12-24 17:30 UTC, TFK70 commented on site/course-description-fragment/src/course-description.component.tsx
> +                      letterSpacing='0.15em'
Это антипаттерн тк здесь не использовался компонентный подход, при изменении навлинка придется делать кучу ручной работы

2021-12-24 17:33 UTC, TFK70 commented on site/course-description-fragment/src/course-description.component.tsx
> +                      letterSpacing='0.15em'
@gochicus и ты так и не добавил transition

2021-12-25 13:45 UTC, gochicus commented on site/course-description-fragment/src/course-description.component.tsx
> +                      letterSpacing='0.15em'
@TFK70 требуется уточнение

> Это антипаттерн тк здесь не использовался компонентный подход, при изменении навлинка придется делать кучу ручной работы

это замечание касается только тех мест, куда нас ведет навигация через якоря? 
https://github.com/torin-asakura/drum-in/pull/27/files/265b2d44198e80890fc97a2662d827b47f9844b0..b63fc50e8fc32fad51eb32e48412f056d54e23b9#diff-cf91a8b0f77c6226eaccfd0bc8a9e83595c0d156f13da7c7259381fceba3c41bR34

2021-12-25 17:34 UTC, TFK70 commented on site/course-description-fragment/src/course-description.component.tsx
> +                      letterSpacing='0.15em'
@gochicus тех мест, где код повторяется, если я правильно вопрос понял

2021-12-25 17:34 UTC, TFK70 commented on site/course-description-fragment/src/course-description.component.tsx
> +                      letterSpacing='0.15em'
Просто у тебя куча стилей у текста которые можно не дублировать

2021-12-27 08:17 UTC, gochicus commented on site/course-description-fragment/src/course-description.component.tsx
> +                      letterSpacing='0.15em'
@TFK70 в общем, реализуя вынесение в компоненты стилей текстов, я начал создавать отдельные компоненты   вроде `IndividualLessonsHeader`, подошёл Андрей и сказал, что это в принципе неправильно. Что вынесение стилей подразумевает компонент Text.  Сейчас я начал это реализовывать создавая стили для Text, примерно таким образом: 
` export const individualLessonsHeaderMobileStyles = ({
    color:'white',
    fontSize: 'small',
    fontWeight:'bold',
    lineHeight:'semiRegular',
    textAlign='center',
    letterSpacing='0.15em'
 })`
Это правильный подход?

2021-12-27 09:03 UTC, TFK70 commented on site/course-description-fragment/src/course-description.component.tsx
> +                      letterSpacing='0.15em'
@gochicus правильного и неправильного нету, у этого подхода есть плюсы и минусы как у всего остального
В целом он имеет место быть, главное чтобы он решал проблему и тебе было с этим комфортно работать

2021-12-27 13:25 UTC, gochicus commented
@TFK70 теперь готово к ревью.

2021-12-27 13:52 UTC, TFK70 requested changes

2021-12-27 13:52 UTC, TFK70 commented on site/address-fragment/src/address.component.tsx
> +      <Layout width='100%'>
Зачем здесь этот контейнер?

2021-12-27 13:52 UTC, TFK70 commented on site/course-description-fragment/src/course-description.component.tsx
> +                      letterSpacing='0.15em'
@gochicus ?

2021-12-27 13:52 UTC, TFK70 commented on site/footer/src/footer.component.tsx
> +    <Layout width={['320px', '320px', '100%']} height={['400px', '400px', '252px']}>
width и height нельзя перенести в Box ниже?

2021-12-27 13:52 UTC, TFK70 commented on site/header-fragment/src/content-render/content-render.compontnet.tsx
> +const ContentRender: FC<string[]> = ({ array }) => {
Что это за типизация такая?

2021-12-27 13:52 UTC, TFK70 commented on site/header-fragment/src/content-render/content-render.compontnet.tsx
> +          <Layout flexBasis={item === array[array.length - 1 - 1] ? [14, 14, 35] : [14, 14, 20]} />
Что тут происходит?

2021-12-27 13:52 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +          <Layout width='300px' overflow='visible' style={{ zIndex: 3 }}>
Тебя устраивает такая работа с zIndex'ами? Ты в голове значения для каждого просчитываешь? Почему 3?

2021-12-27 13:52 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +        <Layout width='320px' style={{ position: 'relative' }}>
Box

2021-12-27 13:52 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +          <Layout width='300px' overflow='visible' style={{ zIndex: 3 }}>
zIndex кстати тоже как проп у Box есть

2021-12-27 13:52 UTC, TFK70 commented on site/individual-lessons-fragment/src/individual-lessons.component.tsx
> +                <Link id='lessons'>
Link с id? Что это?

2021-12-27 13:52 UTC, TFK70 commented on ui/button/src/button.styles.ts
> +export const baseStyles = {
а....что? где createBaseStyles?

2021-12-27 14:45 UTC, gochicus commented
@TFK70  нужна помощь,  не представляю что это за ошибки и откуда они взялись, подозреваю что с самим тайпскриптом что-то не то: 
![image](https://user-images.githubusercontent.com/49765285/147482162-199ce938-1be5-4065-b8eb-822996a9cdd9.png)

Кроме того,  тайпчек показывает, что ни один из пакетов не видит react-intl 
![image](https://user-images.githubusercontent.com/49765285/147482263-a928109d-98ca-4f38-adec-c613419cf3a7.png)
Сам интл при этом работает, текст отображается.

2021-12-27 15:34 UTC, TFK70 commented
@gochicus поэтому нужно добавлять зависимость в devDependencies если она находится в пирах

2021-12-27 15:39 UTC, gochicus commented
@TFK70 в  app devDependencies ?

2021-12-27 15:44 UTC, gochicus commented on site/individual-lessons-fragment/src/individual-lessons.component.tsx
> +                <Link id='lessons'>
@TFK70 уточни, пожалуйста, реквест. Тут якорь, он рабочий.

2021-12-27 15:58 UTC, gochicus commented on site/address-fragment/src/address.component.tsx
> +      <Layout width='100%'>
@TFK70 здесь аналогично этому: 
https://github.com/torin-asakura/drum-in/pull/27#discussion_r773867073

2021-12-27 16:06 UTC, TFK70 commented on site/individual-lessons-fragment/src/individual-lessons.component.tsx
> +                <Link id='lessons'>
почему Link?

2021-12-27 16:10 UTC, TFK70 commented
> @TFK70 в app devDependencies ?

почему в app?

2021-12-27 16:15 UTC, gochicus commented on site/individual-lessons-fragment/src/individual-lessons.component.tsx
> +                <Link id='lessons'>
@TFK70 а, кажется я тебя понял, id я мог повесить любому элементу.

2021-12-27 16:34 UTC, gochicus commented
@TFK70 Хорошо, насчёт devDependencies  ошибку понял, а что насчёт первого скрина? Там значение nowrap свойства  whiteSpace почему-то стало типом. Ну и ошибка  типа какая-то в конфиге некста.

2021-12-27 16:39 UTC, TFK70 commented
@gochicus а что у тебя с текстом вообще? Почему он не из атлантиса?

2021-12-27 16:47 UTC, gochicus commented
@TFK70 я не совсем врубился как расширить стили атлантиса, поэтому сделал свой компонент полностью со своими стилями.  Насчёт некста понял, а что насчёт остальных с первого скрина?   Type nowrap  ставит в тупик, если честно.

2022-01-02 16:16 UTC, TFK70 approved these changes

2022-01-02 16:24 UTC, TorinAsakura approved these changes

2022-01-02 16:24 UTC, merged