feat/main-page
torin-asakura/drum-in pull request #53
Opened 2022-12-29 06:59 UTC by eshevlyakova

2023-01-07 19:29 UTC, TFK70 requested changes
1. В секции "Вопросы и ответы" на тултипах лучше сделать задержку, в районе 2ms, не больше, потому что иначе в глазах рябит очень сильно из-за слишком резкого появления подсказок

Так же на значке i (информация) нужно повесить cursor pointer

![image](https://user-images.githubusercontent.com/62806448/211167138-d358edfd-b796-42ba-9033-0c55001b2323.png)

2. Для всех кнопок на сайте нужно добавить transition, чтобы анимация на ховере была плавной, тоже порядка 2ms, не больше
3. Составлю отдельно задачу насчет параллакс эффекта в секции "во время обучения вас ждет". Swiper не предназначен для таких вещей, эти ленты нужно анимировать вручную, иначе это получается очень дёрганно, и устройство клиента нагружается намного сильнее. Сейчас с этим делать ничего не нужно, сделаем в последнюю очередь, так как решение в целом неплохое

![image](https://user-images.githubusercontent.com/62806448/211167265-cb90a16d-8084-46c2-99bb-3a24098bd7e1.png)

4. В шапке у ссылки "Контакты" нету hover состояния. И ссылкам тоже нужно добавить transition

2023-01-07 19:29 UTC, TFK70 commented on ui/theme/src/theme/fonts.ts
> +  DrukWideCy: 'Druk Wide Cy TT Bold',
Это secondary

2023-01-07 19:29 UTC, TFK70 commented on ui/theme/src/theme/fonts.ts
> +  inter: 'Inter',
И tertiary соответственно

2023-01-07 19:29 UTC, TFK70 commented on package.json
> +    "@emotion/css": "^11.10.0",
Зачем здесь эти зависимости?

2023-01-09 12:34 UTC, TFK70 requested changes
Не добавила задержку на появление тултипа (п1)

2023-01-09 12:34 UTC, TFK70 commented on ui/theme/src/global.styles.tsx
> +        button, a {
Никогда так не делай, у тебя есть button в uikit для этого

2023-01-09 12:34 UTC, TFK70 commented on ui/theme/src/global.styles.tsx
> +        button, a {
Вообще файл globals не трогай, его можно использовать только тогда, когда у тебя нет доступа к компоненту который тебе нужно стилизовать (как свайпер), а так у тебя есть целая button в ui

2023-01-09 12:50 UTC, eshevlyakova commented
@TFK70 
> Не добавила задержку на появление тултипа (п1)

https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-faq/src/list-desktop/item/item.component.tsx#L70

2023-01-09 13:16 UTC, TFK70 commented
> https://github.com/torin-asakura/drum-in/blob/feat/main-page/landing/fragments/landing-faq/src/list-desktop/item/item.component.tsx#L70

Нет, это transition, а нужна задержка, delay, на появлении тултипа, чтобы он не сразу появлялся

2023-01-23 21:20 UTC, TFK70 approved these changes

2023-02-22 12:26 UTC, TorinAsakura requested changes
landing-students почему-то содержит в себе ui компонент модального окна, я не думаю, что он должен там быть, тоже относится и к другим фрагментам

2023-02-22 12:34 UTC, TorinAsakura approved these changes

2023-02-22 12:35 UTC, merged