feat/opening-the-rhythm-page
torin-asakura/drum-in pull request #54
Opened 2023-01-06 16:24 UTC by eshevlyakova

2023-01-07 19:41 UTC, TFK70 requested changes
1. Для тултипов в этой секции на иконке с информацией так же нужно добавить cursor pointer

![image](https://user-images.githubusercontent.com/62806448/211167700-86657f0e-8077-46d2-8e49-30114a605cab.png)

2. С этой кнопкой есть баг: когда наводишься на стрелку над кнопкой - у кнопки пропадает border и иконка

![image](https://user-images.githubusercontent.com/62806448/211167723-a9e9e913-c2eb-4579-b293-19e50a23e81e.png)

3. Для этого элемента тоже нужно добавить cursor pointer

![image](https://user-images.githubusercontent.com/62806448/211167756-c47d41eb-fbb4-4fd5-aedd-d0e68620ceec.png)

2023-01-08 17:31 UTC, eshevlyakova commented
@TFK70 
> С этой кнопкой есть баг: когда наводишься на стрелку над кнопкой - у кнопки пропадает border и иконка

Как для кнопки сделать border с шириной больше 1px?

2023-01-08 18:17 UTC, TFK70 commented
@eshevlyakova То есть? Как обычно, через стили, не понял в чем проблем

2023-01-23 21:18 UTC, TFK70 approved these changes

2023-01-25 08:29 UTC, TorinAsakura requested changes

2023-01-25 08:29 UTC, TorinAsakura commented on landing/fragments/landing-banner-course/src/landing-banner-course.component.tsx
> +                <Row>
Проверь вложенность на предмет бесполезных блоков

2023-02-22 15:23 UTC, TorinAsakura requested changes
если маркируешь компоненты по принадлежности к развёртке (desktop, mobile) то сохраняй консистентный нейминг ${component-name-}+${view}. Далее, если у тебя во фрагменте есть какие-то частные коллекции или чистые компоненты которые используются лишь частно - окей, но нет нужды задавать им постфикс desltop если у них нет другого представления.

2023-02-22 15:27 UTC, TorinAsakura requested changes
Также, по фрагментам заметил много мусорных вложенностей - пройтись по вёрстке

2023-02-22 15:27 UTC, TorinAsakura commented on landing/fragments/landing-skills/src/skills.component.tsx
> +  <Row justifyContent='center'>
зачем тебе блок чтобы выровнять блок?

2023-02-22 17:51 UTC, eshevlyakova commented on landing/fragments/landing-skills/src/skills.component.tsx
> +  <Row justifyContent='center'>
Потому что блок ниже ограничен по ширине (1920px) и с помощью этого дива на больших экранах он отображается посередине

2023-02-23 15:58 UTC, eshevlyakova commented
> Также, по фрагментам заметил много мусорных вложенностей - пройтись по вёрстке

Насчет блока с `<Row justifyContent='center'> ...</Row>` - это помогает делать адаптив на лаптопах

2023-02-27 14:13 UTC, TorinAsakura approved these changes

2023-02-27 14:13 UTC, merged