Feature/drum in backbone
torin-asakura/drum-in pull request #6
Opened 2021-11-22 19:07 UTC by gochicus

#5

2021-11-26 15:39 UTC, TFK70 requested changes

2021-11-26 15:39 UTC, TFK70 commented on site/app/src/pages/index.ts
> +import IndexPage         from '../../../index-page'
Релятивный импорт

2021-11-26 15:39 UTC, TFK70 commented on site/app/src/pages/index.ts
> +/* export default () => createElement('h1', { children: '123' }) */
Это зачем?

2021-11-26 15:39 UTC, TFK70 commented on site/about-fragment/src/mobile/text.component.tsx
> +const TextComponent = ({
Немного не понимаю идею этого компонента

2021-11-26 15:39 UTC, TFK70 commented on site/about-fragment/src/mobile/about-mobile.component.tsx
> +            mainWidth='129px'
Здесь очень абстрактные названия для пропов и их чересчур много, компонент явно намного проще

2021-11-26 15:39 UTC, TFK70 commented on site/course-description-fragment/modal/modal.component.tsx
> +const Modal: FC = ({ show }) => {
А интерфейс?

2021-11-26 15:39 UTC, TFK70 commented on site/course-description-fragment/src/course-description-fragment.component.tsx
> +  const [show, setShow] = useState('none')
Сколько состояний может быть у этой переменной?

2021-11-26 15:39 UTC, TFK70 commented on site/course-description-fragment/src/course-description-fragment.component.tsx
> +            <layout>
html?

2021-11-26 15:39 UTC, TFK70 commented on site/education-fragment/package.json
> +  "packageManager": "yarn@3.0.0",
Зачем это в пекеджах воркспейсов?

2021-11-26 15:39 UTC, TFK70 commented on site/footer/README.md
> +# social
Ридми в футере? Он тут специально оставлен?

2021-11-26 15:39 UTC, TFK70 commented on site/header-fragment/README.md
> +# header-fragment
Не понимаю к чему тут ридмишки

2021-11-26 15:39 UTC, TFK70 commented on site/header-fragment/src/mobile/header-mobile.tsx
> +            <layout>
много хтмла

2021-11-26 15:39 UTC, TFK70 commented on site/header-fragment/src/mobile/header-mobile.tsx
> +          <Box judtifyContent='center' width='255px' height='21px' border='1px solid black'>
опечатка в justifyContent

2021-11-26 15:39 UTC, TFK70 commented on site/header-fragment/src/mobile/header-mobile.tsx
> +          <Box judtifyContent='center' width='255px' height='21px' border='1px solid black'>
их тоже много если что

2021-11-26 15:39 UTC, TFK70 commented on site/header-fragment/src/mobile/header-mobile.tsx
> +        id='ololo'
в проде это вряд ли пригодится)

2021-11-26 15:39 UTC, TFK70 commented on site/header-fragment/src/navigation/navigation.component.tsx
> +        <Layout flrxBasis={11} />
опечатка

2021-11-26 15:39 UTC, TFK70 commented on site/index-page/src/index-page.tsx
> +      <GlobalStyles />
Это должно быть в App

2021-11-26 15:39 UTC, TFK70 commented on site/skills-to-learn-fragment/src/mobile/skills-to-learn-mobile.component.tsx
> +  //TODO add interfaces
Какой интерфейс?

2021-11-26 15:39 UTC, TFK70 commented on site/skills-to-learn-fragment/src/mobile/skills-to-learn-mobile.component.tsx
> +        <SliderComponent marginV={6} height='320px' width='320px' />
Что такое marginV?

2021-11-26 15:39 UTC, TFK70 commented on site/skills-to-learn-fragment/src/mobile/skills-to-learn-mobile.component.tsx
> +        <SliderComponent marginV={6} height='320px' width='320px' />
Если это vertical - используй названия осей (x - горизонтальная, y - вертикальная)

2021-11-26 15:39 UTC, TFK70 commented on ui/layout/src/box.component.tsx
> +export const Box: any = styled('div')(flexbox, color, space, layout, border, position)
`@atls-ui-parts/layout`?

2021-11-26 15:39 UTC, TFK70 commented on ui/layout/src/column.component.tsx
> +export const Column = styled('div')(layout, flexbox, space)
@atls-ui-parts/layout?

2021-11-26 15:39 UTC, TFK70 commented on ui/layout/src/index.ts
> +export * from './text.component'
Почему это в Layout?

2021-11-26 15:39 UTC, TFK70 commented on ui/layout/src/text.component.tsx
> +export const Text = styled('span')(space, flexbox, layout, color, typography)
`@atls-ui-parts/text`

2021-11-26 16:34 UTC, gochicus commented on site/about-fragment/src/mobile/text.component.tsx
> +const TextComponent = ({
@TFK70  нужен для ускорения верстки бэкбоуна, с учётом качества макета.

2021-11-26 16:35 UTC, TFK70 commented on site/about-fragment/src/mobile/text.component.tsx
> +const TextComponent = ({
@gochicus а идея-то какая?

2021-11-27 07:25 UTC, gochicus commented on site/about-fragment/src/mobile/text.component.tsx
> +const TextComponent = ({
@TFK70 В макете разделение на заголовок и основной текст попадается нечасто. Чаще один большой блок с текстом, компонент позволил не городить множество боксов, с вложенными лэйаутами и текстом, а просто задавать размеры в пропсах отдельно для контейнера с заголовком и основным текстом. На этом его функционал пока и ограничивается. Есть тудушка для этого компонента на изменение его таким образом, чтобы он мог принимать и отображать разное содержимое. В целом, это компонент для облегчения верстки в данном конкретном макете. Если что, вынос в ui также планируется и где-то  у меня висит тудушка об этом.

2021-11-27 07:45 UTC, gochicus commented on site/index-page/src/index-page.tsx
> +      <GlobalStyles />
@TFK70  не понял как это должно выглядеть,  посмотрел в misik там в  app  только дефолтный экспорт, а все провайдеры в index page.

2021-11-27 08:16 UTC, gochicus commented on site/about-fragment/src/mobile/about-mobile.component.tsx
> +            mainWidth='129px'
@TFK70  пропсы управляют следующим: два пропса задают  высоту и ширину всего контейнера, два высоту и ширину заголовка, два  ширину и высоту основного текста.  Пропс дисплэй обрабатывает ситуацию, когда нам не нужен заголовок.  Высота и ширина для трех элементов в компоненте. Так мне названия пропсов поменять, можешь уточнить замечание?

2021-11-27 10:00 UTC, TFK70 commented on site/index-page/src/index-page.tsx
> +      <GlobalStyles />
@gochicus какой дефолтный экспорт? Я тебе в мисике говорил только структуру проекта посмотреть
GlobalStyles засунь в ThemeProvider
Где ты видел чтобы глобальные стили вот так применялись?

2021-11-27 10:46 UTC, gochicus commented on site/index-page/src/index-page.tsx
> +      <GlobalStyles />
@TFK70 где -то вычитал, сходу не могу найти, они применялись. Сейчас  пытаюсь как в мисик сделать., но там ошибки, скину в телегу код.

2021-11-29 18:38 UTC, TFK70 commented on site/skills-presentation-fragment/src/skills-presentation.component.tsx
> +            <Layout flexBasis={30} flexShrink={0} />
Что-то тут подозрительно много флекс шринков, они чем-то обоснованы?

2021-11-29 19:18 UTC, gochicus commented on site/skills-presentation-fragment/src/skills-presentation.component.tsx
> +            <Layout flexBasis={30} flexShrink={0} />
@TFK70 в основном, необходимостью "приколотить" отступы.  Но, я учту твоё замечание, и, как закончу с основным бэкбоуном, проведу рефактор для улучшения читаемости, а также постараюсь убрать то лишнее, что найду.

2021-11-30 12:16 UTC, TFK70 requested changes
Красная лента справа должна быть как будто единой (иметь одну и ту же позицию до и после блока с онлайн курсом). У тебя она спозиционирована в каждом месте по-разному

![image](https://user-images.githubusercontent.com/62806448/144045642-61e4702a-ddc2-42e1-aed8-2137b40abdaa.png)

2021-11-30 12:16 UTC, TFK70 commented on site/education-fragment/src/education.component.tsx
> +            <Layout>
Тоже: контейнер внутри контейнера

2021-11-30 12:16 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +    position={['relative', 'relative', 'relative']}
?

2021-11-30 12:16 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +      <Box width='100%' zIndex={[1, 1, 5]} position={['relative', 'relative', 'relative']}>
и тут

2021-11-30 12:16 UTC, TFK70 commented on site/index-page/src/index-page.tsx
> +        <Desktop />
Desktop?

2021-11-30 12:16 UTC, TFK70 commented on site/reviews-fragment/src/reviews.component.tsx
> +              <Box width='3px' height='3px' border='1px solid black' borderRadius={50} />
Тоже буллиты без контейнера?

2021-11-30 12:16 UTC, TFK70 commented on site/skills-presentation-fragment/src/skills-presentation.component.tsx
> +      <Column width='100%' display={['none', 'none', 'flex']}>
Ты все это вручную прописал?
![image](https://user-images.githubusercontent.com/62806448/144044893-60736807-1f86-4cda-9ddf-c7f2314b18e4.png)

2021-11-30 12:16 UTC, TFK70 commented on site/skills-presentation-fragment/src/skills-presentation.component.tsx
> +      <Column width='100%' display={['none', 'none', 'flex']}>
И да, блок слева должен немного выступать за основной контейнер

2021-11-30 12:16 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn-desktop.component.tsx
> +const SkillsToLearnDesktop = () => (
desktop?

2021-11-30 12:16 UTC, TFK70 commented on site/skills-to-learn-fragment/src/skills-to-learn-mobile.component.tsx
> +const SkillsToLearnMobile = () => (
mobile? Ты же это все поправить должен был?

2021-11-30 12:16 UTC, TFK70 commented on ui/condition/src/condition.component.tsx
> +const Condition = ({ match, children }) => match && children
Советую писать `match ? children : null`
Когда компонент возвращает undefined - это не совсем валидно для реакта

2021-11-30 12:23 UTC, TFK70 requested changes

2021-11-30 12:23 UTC, TFK70 commented on site/individual-lessons-fragment/src/individual-lessons.component.tsx
> +    <IndividualLessonsMobile/>
А почему ты так разделяешь десктоп/мобилку? Это делается через styled-system в одном файле, как обычно

2021-11-30 13:28 UTC, gochicus commented on site/course-description-fragment/src/course-description-fragment.component.tsx
> +          <Layout>
@TFK70  в данном случае ( и во всех аналогичных)   Box  просто оборачивает контейнер, чтобы использовать  бордер для проверки позиционирования элемента. Если, конечно, ты не имел ввиду что-то другое.  Мне  что, нужно убрать боксы с бордерами?

2021-11-30 17:05 UTC, TFK70 commented on site/course-description-fragment/src/course-description-fragment.component.tsx
> +          <Layout>
А зачем тогда эти боксы с бордерами нужны? Они и отображают твои контейнеры

2021-11-30 17:06 UTC, TFK70 commented on site/course-description-fragment/src/course-description-fragment.component.tsx
> +          <Layout>
В будущем ты должен убрать только бордер и все - контейнер готов

2021-12-01 12:07 UTC, gochicus commented on site/course-description-fragment/src/course-description-fragment.component.tsx
> +          <Layout>
@TFK70  Проясни ситуацию, вот у меня есть текст, который оборачивается в Layout, я хочу обозначить этот текст на макете, но Layout  не имеет border, по умолчанию он не проброшен из styed-system.  Зато Box  имеет Border, верстать  текс в боксе было бы семантически неправильно, поэтому я и оборачиваю  весь  элемент в Box.  Из  твоих ответов мне не ясно что делать, я убираю боксы и пробрасываю border в Layout, или убираю Layout внутри  Box.  Можешь прояснить какие изменения я должен внести?

2021-12-02 07:33 UTC, gochicus commented on site/course-description-fragment/modal/modal.interface.ts
> +  show: string
@TFK70  я пока убрал show, он на данном этапе не вписывается., поскольку логика под него не проработана, коммит сегодня запушу.

2021-12-06 18:19 UTC, TFK70 approved these changes

2021-12-06 20:09 UTC, TorinAsakura commented on ui/button/src/button.component.tsx
> +// TODO change button component
что это? что значит "поменять компонент кнопки"?

2021-12-06 20:09 UTC, TorinAsakura commented on ui/input/src/input.component.tsx
> +  // TODO change Input
?

2021-12-06 20:10 UTC, TorinAsakura commented on ui/theme/README.md
> +# theme
о чём проект?

2021-12-06 20:10 UTC, TorinAsakura commented on ui/theme/src/global.styles.tsx
> +        display: flex;
зачем тут дисплей флекс? глобально задавать такое может быть чревато неожиданными последствиями

2021-12-06 20:11 UTC, TorinAsakura requested changes

2021-12-06 20:11 UTC, TorinAsakura commented on ui/theme/src/global.styles.tsx
> +        flex-direction: column;
зачем?

2021-12-08 15:19 UTC, TFK70 approved these changes

2021-12-08 17:36 UTC, TorinAsakura approved these changes

2021-12-08 17:36 UTC, merged