feat/contact-page
torin-asakura/drum-in pull request #61
Opened 2023-01-13 11:06 UTC by eshevlyakova

2023-01-23 21:19 UTC, TFK70 approved these changes

2023-02-23 13:29 UTC, TorinAsakura requested changes

2023-02-23 13:29 UTC, TorinAsakura commented on landing/fragments/landing-contact/src/contact.component.tsx
> +            <Card
почта, телега, телефон - это ссылки

2023-02-23 16:02 UTC, eshevlyakova commented on landing/fragments/landing-contact/src/contact.component.tsx
> +            <Card
Ссылкой является [весь прямоугольник](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=1056%3A3932&t=h6dVIpm8RTp4DTxH-4) или только сама надпись (к примеру: marina@drum.ru)?

2023-02-27 14:06 UTC, TorinAsakura commented on landing/fragments/landing-contact/src/contact.component.tsx
> +              href='https://t.me/marinaaa'
в ссылках, также, нужно указывать разного рода (и назначения) атрибуты, в данном случае было бы неплохо добавить nofollow и target

2023-02-27 14:12 UTC, TorinAsakura approved these changes

2023-02-27 14:12 UTC, merged