feat/form-and-payment
torin-asakura/drum-in pull request #66
Opened 2023-01-19 11:52 UTC by eshevlyakova

2023-02-27 15:44 UTC, TorinAsakura requested changes

2023-02-27 15:44 UTC, TorinAsakura commented on landing/fragments/landing-consultation/src/container/index.ts
> +export * from './container.component'
почему ui компонент опять во фрагментах?

2023-02-27 15:44 UTC, TorinAsakura commented on landing/fragments/landing-modal-forms/src/container/index.ts
> +export * from './container.component'
зачем ты копипастишь один и тот же код в разные пакеты?

2023-02-27 16:00 UTC, eshevlyakova commented on landing/fragments/landing-modal-forms/src/individual-course-content/selected-course/info/info.component.tsx
> +          color={isOpen ? 'rgb(15,12,12)' : 'rgb(242,242,242)'}
У меня в [объекте цветов](https://github.com/torin-asakura/drum-in/blob/feat/form-and-payment/ui/theme/src/theme/colors.ts) хранятся другие объекты. И когда я буду писать к примеру color='background.smokyWhite', то это не будет работать. 
Я могу убрать все внутренние объекты и оставить только для button, тогда смогу для всех иконок брать цвета из темы

2023-02-27 17:16 UTC, TorinAsakura commented on landing/fragments/landing-modal-forms/src/individual-course-content/selected-course/info/info.component.tsx
> +          color={isOpen ? 'rgb(15,12,12)' : 'rgb(242,242,242)'}
> У меня в [объекте цветов](https://github.com/torin-asakura/drum-in/blob/feat/form-and-payment/ui/theme/src/theme/colors.ts) хранятся другие объекты. И когда я буду писать к примеру color='background.smokyWhite', то это не будет работать.
> Я могу убрать все внутренние объекты и оставить только для button, тогда смогу для всех иконок брать цвета из темы. Делать?

Я ничего не понял, какие другие объекты? Почему что не будет работать? Ничего не понимаю…

2023-02-27 17:26 UTC, eshevlyakova commented on landing/fragments/landing-modal-forms/src/individual-course-content/selected-course/info/info.component.tsx
> +          color={isOpen ? 'rgb(15,12,12)' : 'rgb(242,242,242)'}
> какие другие объекты?

В [объекте colors](https://github.com/torin-asakura/drum-in/blob/feat/form-and-payment/ui/theme/src/theme/colors.ts) есть вложенные объекты (к примеру text, background)

> Почему что не будет работать? 

Не будет работать потому что для атрибута иконки color, [как я поняла](https://github.com/torin-asakura/drum-in/blob/feat/form-and-payment/ui/icons/src/ArrowBottomIcon.tsx#L21) не поддерживается вложенность объектов. 
Я смотрела примеры и когда в иконках используются цвета из компонентной базы, то объект color выглядит [так](https://github.com/torin-asakura/shdvor/blob/master/ui/theme/src/theme/colors.ts), то есть цвета находятся на верхнем уровне вложенности

2023-02-27 19:50 UTC, TorinAsakura commented on landing/fragments/landing-modal-forms/src/individual-course-content/selected-course/info/info.component.tsx
> +          color={isOpen ? 'rgb(15,12,12)' : 'rgb(242,242,242)'}
Ладно, код бы с ним, потом разберёмся когда будем с данными работать, поправь остальное и ок

2023-02-28 16:07 UTC, TorinAsakura requested changes

2023-02-28 16:07 UTC, TorinAsakura commented on landing/fragments/landing-modal-forms/src/modal-mobile-forms.component.tsx
>  import { Backdrop }                                from './backdrop'
backdrop это ui компонент модального окна, что он тут делает во фрагменте?

2023-02-28 19:33 UTC, TorinAsakura commented on ui/switch/src/option/option.component.tsx
> +            else push()
объяснишь?

2023-02-28 19:34 UTC, TorinAsakura approved these changes

2023-02-28 19:34 UTC, merged

2023-03-01 03:34 UTC, eshevlyakova commented on ui/switch/src/option/option.component.tsx
> +            else push()
При клике на кнопку, если includes не пустая строка (то есть true) - срабатывает функция remove (в ней фильтруется массив), иначе срабатывает функция push () в зависимости от значения mutuallyExclusive (который задается для каждого option), либо добавит в конец массива данную строку, либо удалит все элементы и добавит одну эту строку